In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
train_part1 = pd.read_parquet("../data/train_part_1.parquet", engine='fastparquet')

Сравним с предыдущим набором

In [3]:
train_part1.info()

<class 'pandas.DataFrame'>
RangeIndex: 28618594 entries, 0 to 28618593
Data columns (total 23 columns):
 #   Column                      Dtype
---  ------                      -----
 0   customer_id                 int64
 1   event_id                    int64
 2   event_dttm                  object
 3   event_type_nm               int32
 4   event_desc                  int32
 5   channel_indicator_type      int32
 6   channel_indicator_sub_type  int32
 7   operaton_amt                float64
 8   currency_iso_cd             float64
 9   mcc_code                    object
 10  pos_cd                      float64
 11  accept_language             object
 12  browser_language            object
 13  timezone                    float64
 14  session_id                  float64
 15  operating_system_type       float64
 16  battery                     object
 17  device_system_version       object
 18  screen_size                 object
 19  developer_tools             object
 20  phone_voip_call_state       float64
 21  web_rdp_connection          float64
 22  compromised                 object
dtypes: float64(8), int32(4), int64(2), object(9)
memory usage: 4.5+ GB

In [4]:
train_part1.head(5)

,customer_id,event_id,event_dttm,event_type_nm,event_desc,channel_indicator_type,channel_indicator_sub_type,operaton_amt,currency_iso_cd,mcc_code,...,timezone,session_id,operating_system_type,battery,device_system_version,screen_size,developer_tools,phone_voip_call_state,web_rdp_connection,compromised
0,123123123123129,123999300382879,2024-10-01 05:29:14,14,75,6,5,56422.0,0.0,4,...,NaN,NaN,NaN,None,None,None,None,NaN,NaN,None
1,123123123123129,124531875713936,2024-10-01 10:17:22,7,56,4,15,NaN,NaN,None,...,NaN,NaN,NaN,None,None,None,None,NaN,NaN,None
2,123123123123129,123329285580171,2024-10-01 10:20:03,3,120,6,5,300870.0,0.0,10,...,NaN,NaN,NaN,None,None,None,None,NaN,NaN,None
3,123123123123129,124334305430665,2024-10-02 07:48:09,14,75,6,5,298458.0,0.0,1,...,NaN,NaN,NaN,None,None,None,None,NaN,NaN,None
4,123123123123129,126215501146513,2024-10-02 11:20:40,14,75,6,5,59944.0,0.0,15,...,NaN,NaN,NaN,None,None,None,None,NaN,NaN,None

In [5]:
def most_popular(dataframe):            
    cols = dataframe.columns
    for i in cols:
        print(f"{i}:")
        print(f"{dataframe[i].mode(dropna=False)}\n")

In [6]:
most_popular(train_part1)

customer_id:
0    123166072796364
Name: customer_id, dtype: int64

event_id:
0           123123123123263
1           123123123126557
2           123123123126655
3           123123123126784
4           123123123127994
                 ...
28618589    126550511519551
28618590    126550511523138
28618591    126550511525464
28618592    126550511527439
28618593    126550511527670
Name: event_id, Length: 28618594, dtype: int64

event_dttm:
0    2024-10-18 10:33:24
1    2024-12-27 12:47:12
2    2025-05-15 10:09:40
Name: event_dttm, dtype: object

event_type_nm:
0    7
Name: event_type_nm, dtype: int32

event_desc:
0    56
Name: event_desc, dtype: int32

channel_indicator_type:
0    4
Name: channel_indicator_type, dtype: int32

channel_indicator_sub_type:
0    15
Name: channel_indicator_sub_type, dtype: int32

operaton_amt:
0   NaN
Name: operaton_amt, dtype: float64

currency_iso_cd:
0    0.0
Name: currency_iso_cd, dtype: float64

mcc_code:
0    None
Name: mcc_code, dtype: object

pos_cd:
0   NaN
Name: pos_cd, dtype: float64

accept_language:
0    None
Name: accept_language, dtype: object

browser_language:
0    None
Name: browser_language, dtype: object

timezone:
0   NaN
Name: timezone, dtype: float64

session_id:
0   NaN
Name: session_id, dtype: float64

operating_system_type:
0   NaN
Name: operating_system_type, dtype: float64

battery:
0    None
Name: battery, dtype: object

device_system_version:
0    None
Name: device_system_version, dtype: object

screen_size:
0    None
Name: screen_size, dtype: object

developer_tools:
0    None
Name: developer_tools, dtype: object

phone_voip_call_state:
0   NaN
Name: phone_voip_call_state, dtype: float64

web_rdp_connection:
0   NaN
Name: web_rdp_connection, dtype: float64

compromised:
0    None
Name: compromised, dtype: object

In [7]:
cols = train_part1.columns
for i in range(23):
    print(f"{train_part1[cols[i]].value_counts(dropna=False)}\n")

customer_id
123166072796364    3376
123277741949059    3056
123432360770994    3011
123286331880824    2877
123260562078628    2838
                   ...
123140302997224      58
123174662734089      57
123329281556836      53
123449540641697      47
123475310445074      45
Name: count, Length: 33333, dtype: int64

event_id
123999300382879    1
124531875713936    1
123329285580171    1
124334305430665    1
126215501146513    1
                  ..
126490381958304    1
124128146411089    1
125433819853542    1
126215503301577    1
126052293072084    1
Name: count, Length: 28618594, dtype: int64

event_dttm
2024-10-18 10:33:24    14
2025-05-15 10:09:40    14
2024-12-27 12:47:12    14
2025-02-15 09:01:30    13
2024-12-02 11:08:00    13
                       ..
2025-05-10 12:46:56     1
2025-05-16 11:38:21     1
2025-05-17 02:59:25     1
2025-05-17 10:48:09     1
2025-05-25 09:16:59     1
Name: count, Length: 13374722, dtype: int64

event_type_nm
7     11945911
14    11657184
8      2076315
9      1397391
11      771410
2       345056
3       246317
10       60974
6        28784
4        28206
0        19933
15       16205
16       14851
12        3917
5         3128
13        2982
1           30
Name: count, dtype: int64

event_desc
56     11954067
75      7561725
36      1923232
86      1827518
48       767013
         ...
157           1
156           1
127           1
142           1
161           1
Name: count, Length: 143, dtype: int64

channel_indicator_type
4    14769701
0     8298345
3     4782622
1      472826
6      175432
2      119476
5         192
Name: count, dtype: int64

channel_indicator_sub_type
15    14040044
5      8400832
4      4856311
14      889622
0       116800
16      116730
7        61078
12       55957
2        54085
11       19712
1         4706
3         1824
8          697
13         191
10           4
6            1
Name: count, dtype: int64

operaton_amt
NaN         13353367
0.0            73227
100.0          16379
101.0           8379
99.0            8360
              ...
555472.0           1
580429.0           1
940002.0           1
545566.0           1
541772.0           1
Name: count, Length: 1094899, dtype: int64

currency_iso_cd
0.0     15604232
NaN     12996950
7.0        10468
8.0         5156
2.0          519
6.0          333
1.0          298
5.0          246
3.0          189
4.0          117
17.0          19
13.0          19
11.0          13
9.0            9
10.0           9
15.0           9
12.0           4
21.0           2
24.0           1
20.0           1
Name: count, dtype: int64

mcc_code
None    20440094
4        3804765
10        899120
15        781895
17        649169
9         358092
1         323720
19        321235
7         248855
14        211199
16        180184
18         90616
2          89472
3          80808
0          29521
13         25565
6          24425
11         18818
8          15578
5          13506
12         11957
Name: count, dtype: int64

pos_cd
NaN     26134680
3.0      1634195
1.0       749494
14.0       33381
8.0        30394
10.0       17454
9.0         7966
4.0         6027
16.0        2342
11.0         872
2.0          726
12.0         317
13.0         217
7.0          170
5.0          114
17.0          77
19.0          75
0.0           57
6.0           18
18.0          13
15.0           3
23.0           1
20.0           1
Name: count, dtype: int64

accept_language
None                                                        25452822
ru                                                           2596882
ru-ru                                                         361905
ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7                           133580
ru,en;q=0.9                                                    16963
                                                              ...
ru,en;q=0.9,en-GB;q=0.8,en-US;q=0.7,kk;q=0.6                       1
ru-RU,ru;q=0.9,be-RU;q=0.8,be;q=0.7,en-US;q=0.6,en;q=0.5           1
ru-GB,ru-RU;q=0.9,ru;q=0.8,en-US;q=0.7,en;q=0.6                    1
ru,en;q=0.9,ja;q=0.8,de;q=0.7,es;q=0.6                             1
ru-RU,ru;q=0.9,fr-TN;q=0.8,fr;q=0.7,en-US;q=0.6,en;q=0.5           1
Name: count, Length: 375, dtype: int64

browser_language
None                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           25968210
not available                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   2650358
:not available,systemLanguage:not available,userLanguage:not available,iframed:false,intip:945012c0-54bc-44e5-9194-e73f30281068.local,battery:100%,reducedMotion:false,mouseTimingV1:[],userAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,webdriver:false,language:ru-RU,colorDepth:24,deviceMemory:8,pixelRatio:1,hardwareConcurrency:4,screenResolution:900,1600,availableScreenResolution:860,1600,timezoneOffset:-180,timezone:Europe/Moscow,sessionStorage:true,localStorage:true,indexedDb:true,addBehavior:false,openDatabase:false,cpuClass:not available,platform:Win32,plugins:Alipay Security Control 3,Alipay Security Control,application/x-alisecctrl-plugin,*,Alipay security control,npaliedit,application/aliedit,,Chromium PDF Plugin,Portable Document Format,application/x-google-chrome-pdf,pdf,Chromium PDF Viewer,,application/pdf,pdf,Microsoft Office,The plugin allows you to have a better experience with Microsoft SharePoint,application/x-sharepoint,,application/x-sharepoint-uc,,Microsoft® Windows Media Player Firefox Plugin,np-mswmp,application/x-ms-wmp,*,application/asx,*,video/x-ms-asf-plugin,*,application/x-mplayer2,*,video/x-ms-asf,asf,asx,*,video/x-ms-wm,wm,*,audio/x-ms-wma,wma,*,audio/x-ms-wax,wax,*,video/x-ms-wmv,wmv,*,video/x-ms-wvx,wvx,*,PDF-XChangeВ® Editor,PDF-XChange Editor Netscape Gecko Plugin,application/pdf,pdf,application/vnd.fdf,fdf,application/vnd.adobe.xfdf,xfdf,PDF-XChangeВ® Editor,PDF-XChange Editor Netscape Gecko Plugin,application/pdf,pdf,application/vnd.fdf,fdf,application/vnd.adobe.xfdf,xfdf,Shockwave Flash,Shockwave Flash 32.0 r0,application/x-shockwave-flash,swf,application/futuresplash,spl,Shockwave Flash,Shockwave Flash 32.0 r0,application/x-shockwave-flash,swf,application/futuresplash,spl,iTrusChina iTrusPTA,XEnroll,iEnroll,hwPTA,UKeyInstalls Firefox Plugin,iTrusPTA                                                                                                                                      3
:not available,iframed:false,intip:ba58c52d-923e-4ede-ba62-7da1af5ad25d.local,battery:100%,User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,reducedMotion:false,mouseTimingV1:[[2.772588722239781,2.833213344056216,2.833213344056216,2.8101716064043196,0.0393388482697929]],userAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,webdriver:false,language:ru-RU,colorDepth:24,deviceMemory:4,pixelRatio:1.25,hardwareConcurrency:4,screenResolution:864,1536,availableScreenResolution:824,1536,timezoneOffset:-180,timezone:Europe/Moscow,sessionStorage:true,localStorage:true,indexedDb:true,openDatabase:false,platform:Win32,plugins:Alipay Security Control 3,Alipay Security Control,application/x-alisecctrl-plugin,*,Alipay security control,npaliedit,application/aliedit,,Chromium PDF Plugin,Portable Document Format,application/x-google-chrome-pdf,pdf,Chromium PDF Viewer,,application/pdf,pdf,Microsoft Office,The plugin allows you to have a better experience with Microsoft SharePoint,application/x-sharepoint,,application/x-sharepoint-uc,,Microsoft® Windows Media Player Firefox Plugin,np-mswmp,application/x-ms-wmp,*,application/asx,*,video/x-ms-asf-plugin,*,application/x-mplayer2,*,video/x-ms-asf,asf,asx,*,video/x-ms-wm,wm,*,audio/x-ms-wma,wma,*,audio/x-ms-wax,wax,*,video/x-ms-wmv,wmv,*,video/x-ms-wvx,wvx,*,iTrusChina iTrusPTA,XEnroll,iEnroll,hwPTA,UKeyInstalls Firefox Plugin,iTrusPTA                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          3
:not available,iframed:false,intip:1ea3a92f-c7ea-4305-9723-3fb418ed1df4.local,battery:100%,User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,reducedMotion:false,mouseTimingV1:[[2.772588722239781,2.833213344056216,2.833213344056216,2.8421159104939644,0.14389368590311588],[2.772588722239781,2.833213344056216,3.337280695907213,2.9510307495766006,0.5279652647041363],[2.772588722239781,2.833213344056216,3.836611560560854,3.0496050788346,0.7159712071442551]],userAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,webdriver:false,language:ru-RU,colorDepth:24,deviceMemory:4,pixelRatio:1,hardwareConcurrency:8,screenResolution:900,1440,availableScreenResolution:860,1440,timezoneOffset:-180,timezone:Europe/Moscow,sessionStorage:true,localStorage:true,indexedDb:true,openDatabase:false,platform:Win32,plugins:Alipay Security Control 3,Alipay Security Control,application/x-alisecctrl-plugin,*,Alipay security control,npaliedit,application/aliedit,,Chromium PDF Plugin,Portable Document Format,application/x-google-chrome-pdf,pdf,Chromium PDF Viewer,,application/pdf,pdf,CryptoPro CAdES NPAPI Browser Plug-in,CryptoPro CAdES NPAPI Browser Plug-in,application/x-cades,,Microsoft® Windows Media Player Firefox Plugin,np-mswmp,application/x-ms-wmp,*,application/asx,*,video/x-ms-asf-plugin,*,application/x-mplayer2,*,video/x-ms-asf,asf,asx,*,video/x-ms-wm,wm,*,audio/x-ms-wma,wma,*,audio/x-ms-wax,wax,*,video/x-ms-wmv,wmv,*,video/x-ms-wvx,wvx,*,Shockwave Flash,Shockwave Flash 32.0 r0,application/x-shockwave-flash,swf,application/futuresplash,spl,iTrusChina iTrusPTA,XEnroll,iEnroll,hwPTA,UKeyInstalls Firefox Plugin,iTrusPTA                                                                                                                                                                                                                                                               2
:not available,iframed:false,intip:f02a0cfc-d02f-412e-8b39-d140112ceed6.local,battery:100%,User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,reducedMotion:false,mouseTimingV1:[[2.70805020110221,2.833213344056216,2.8903717578961645,2.995555661489224,0.7960741499346485],[2.772588722239781,2.833213344056216,2.8903717578961645,2.863598699696401,0.24813021951139563],[2.772588722239781,2.833213344056216,4.54000193512409,3.2093592728755627,0.852849******7714],[2.772588722239781,2.833213344056216,4.905165027024939,3.323481944372623,1.025357408608629]],userAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,webdriver:false,language:ru-RU,colorDepth:24,deviceMemory:4,pixelRatio:1.25,hardwareConcurrency:4,screenResolution:864,1536,availableScreenResolution:824,1536,timezoneOffset:-180,timezone:Europe/Moscow,sessionStorage:true,localStorage:true,indexedDb:true,openDatabase:false,platform:Win32,plugins:Alipay Security Control 3,Alipay Security Control,application/x-alisecctrl-plugin,*,Alipay security control,npaliedit,application/aliedit,,Chromium PDF Plugin,Portable Document Format,application/x-google-chrome-pdf,pdf,Chromium PDF Viewer,,application/pdf,pdf,Microsoft Office,The plugin allows you to have a better experience with Microsoft SharePoint,application/x-sharepoint,,application/x-sharepoint-uc,,Microsoft® Windows Media Player Firefox Plugin,np-mswmp,application/x-ms-wmp,*,application/asx,*,video/x-ms-asf-plugin,*,application/x-mplayer2,*,video/x-ms-asf,asf,asx,*,video/x-ms-wm,wm,*,audio/x-ms-wma,wma,*,audio/x-ms-wax,wax,*,video/x-ms-wmv,wmv,*,video/x-ms-wvx,wvx,*,iTrusChina iTrusPTA,XEnroll,iEnroll,hwPTA,UKeyInstalls Firefox Plugin,iTrusPTA                                                                                                                                                                                                                   2
:not available,iframed:false,intip:2abb1272-fbd8-4d35-897d-b0ee3e862cfd.local,battery:0%,User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,reducedMotion:false,mouseTimingV1:[[2.772588722239781,2.833213344056216,5.484960471420001,3.38368026142383,1.3704421636579194]],userAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,webdriver:false,language:ru-RU,colorDepth:24,deviceMemory:8,pixelRatio:1,hardwareConcurrency:4,screenResolution:1920,1080,availableScreenResolution:1920,1040,timezoneOffset:-180,timezone:Europe/Moscow,sessionStorage:true,localStorage:true,indexedDb:true,openDatabase:false,platform:Win32,plugins:Adobe Acrobat,Adobe PDF Plug-In For Firefox and Netscape 24.5.20399,application/pdf,pdf,application/vnd.adobe.pdfxml,pdfxml,application/vnd.adobe.x-mars,mars,application/vnd.fdf,fdf,application/vnd.adobe.xfdf,xfdf,application/vnd.adobe.xdp+xml,xdp,application/vnd.adobe.xfd+xml,xfd,Alipay Security Control 3,Alipay Security Control,application/x-alisecctrl-plugin,*,Alipay security control,npaliedit,application/aliedit,,Chromium PDF Plugin,Portable Document Format,application/x-google-chrome-pdf,pdf,Chromium PDF Viewer,,application/pdf,pdf,Microsoft Office 2016,The plugin allows you to have a better experience with Microsoft SharePoint,application/x-sharepoint,,application/x-sharepoint-uc,,Microsoft® Windows Media Player Firefox Plugin,np-mswmp,application/x-ms-wmp,*,application/asx,*,video/x-ms-asf-plugin,*,application/x-mplayer2,*,video/x-ms-asf,asf,asx,*,video/x-ms-wm,wm,*,audio/x-ms-wma,wma,*,audio/x-ms-wax,wax,*,video/x-ms-wmv,wmv,*,video/x-ms-wvx,wvx,*,iTrusChina iTrusPTA,XEnroll,iEnroll,hwPTA,UKeyInstalls Firefox Plugin,iTrusPTA                                                                                                                                                                                                                1

In [8]:
train_part1.drop(columns=["event_dttm", "accept_language", "device_system_version", "browser_language", "screen_size", "battery"]).corr()

,customer_id,event_id,event_type_nm,event_desc,channel_indicator_type,channel_indicator_sub_type,operaton_amt,currency_iso_cd,mcc_code,pos_cd,timezone,session_id,operating_system_type,developer_tools,phone_voip_call_state,web_rdp_connection,compromised
customer_id,1.000000,0.000166,0.002786,0.000809,-0.002097,-0.001194,-0.001411,-0.001777,0.004853,0.005461,-0.010480,0.000149,-0.019038,-0.011441,-0.000049,0.020437,0.007298
event_id,0.000166,1.000000,-0.000229,0.000128,-0.000004,0.000138,-0.000555,-0.000053,0.000129,0.000355,0.000331,0.000538,-0.001012,0.000233,-0.000238,0.000362,0.000124
event_type_nm,0.002786,-0.000229,1.000000,0.072384,-0.524311,-0.356222,-0.002140,-0.026136,-0.103191,-0.192624,-0.011046,0.000113,-0.051402,-0.001656,0.000139,0.048211,-0.005155
event_desc,0.000809,0.000128,0.072384,1.000000,-0.467516,-0.336685,-0.000302,0.019911,0.014639,0.056774,-0.002135,0.000488,-0.002162,-0.000251,-0.000935,0.017924,-0.001660
channel_indicator_type,-0.002097,-0.000004,-0.524311,-0.467516,1.000000,0.741870,0.004310,-0.025096,0.001021,0.029392,0.000900,-0.000016,0.000010,0.002232,-0.000609,0.000094,0.000419
channel_indicator_sub_type,-0.001194,0.000138,-0.356222,-0.336685,0.741870,1.000000,0.009070,-0.021488,0.009561,0.160798,-0.001256,-0.000107,0.000956,0.002187,-0.000506,0.006183,0.000428
operaton_amt,-0.001411,-0.000555,-0.002140,-0.000302,0.004310,0.009070,1.000000,0.002833,0.023650,0.031784,0.002245,0.000264,-0.008470,0.002630,0.007196,0.002749,-0.000397
currency_iso_cd,-0.001777,-0.000053,-0.026136,0.019911,-0.025096,-0.021488,0.002833,1.000000,0.011713,0.001197,0.001195,0.000377,-0.002448,0.000664,0.003718,0.011448,-0.000335
mcc_code,0.004853,0.000129,-0.103191,0.014639,0.001021,0.009561,0.023650,0.011713,1.000000,-0.073881,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pos_cd,0.005461,0.000355,-0.192624,0.056774,0.029392,0.160798,0.031784,0.001197,-0.073881,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
timezone,-0.010480,0.000331,-0.011046,-0.002135,0.000900,-0.001256,0.002245,0.001195,NaN,NaN,1.000000,-0.001034,-0.013769,NaN,NaN,-0.017503,NaN
session_id,0.000149,0.000538,0.000113,0.000488,-0.000016,-0.000107,0.000264,0.000377,NaN,NaN,-0.001034,1.000000,0.001264,-0.000063,0.000723,-0.000129,-0.000523
operating_system_type,-0.019038,-0.001012,-0.051402,-0.002162,0.000010,0.000956,-0.008470,-0.002448,NaN,NaN,-0.013769,0.001264,1.000000,NaN,NaN,-0.056110,NaN
developer_tools,-0.011441,0.000233,-0.001656,-0.000251,0.002232,0.002187,0.002630,0.000664,NaN,NaN,NaN,-0.000063,NaN,1.000000,0.005053,NaN,0.038678
phone_voip_call_state,-0.000049,-0.000238,0.000139,-0.000935,-0.000609,-0.000506,0.007196,0.003718,NaN,NaN,NaN,0.000723,NaN,0.005053,1.000000,NaN,-0.000317
web_rdp_connection,0.020437,0.000362,0.048211,0.017924,0.000094,0.006183,0.002749,0.011448,NaN,NaN,-0.017503,-0.000129,-0.056110,NaN,NaN,1.000000,NaN
compromised,0.007298,0.000124,-0.005155,-0.001660,0.000419,0.000428,-0.000397,-0.000335,NaN,NaN,NaN,-0.000523,NaN,0.038678,-0.000317,NaN,1.000000

- *channel_indicator_type* и *channel_indicator_sub_type*

In [9]:
# delete = ["accept_language", "browser_language", "timezone", "session_id", "operating_system_type", \
#         "battery", "device_system_version", "screen_size"]

# train_part1.drop(columns=delete, inplace=True)

In [10]:
#########
train_part1.fillna(value=-1, inplace=True)
train_part1["phone_voip_call_state"] = train_part1["phone_voip_call_state"].astype(dtype="int16")
train_part1["web_rdp_connection"] = train_part1["web_rdp_connection"].astype(dtype="int16")

In [11]:
train_part1["Hour"] = pd.to_datetime(train_part1["event_dttm"]).dt.hour
train_part1.drop(columns="event_dttm", inplace=True)

#### Добавим таргет и преобразуем его

In [13]:
labels = pd.read_parquet("../data/train_labels.parquet", engine='fastparquet')

In [14]:
labels.head()

       customer_id         event_id  target
0  123123123123129  124093788813382       0
1  123123123123138  126035112904381       0
2  123123123123169  124325714018852       1
3  123123123123169  124944191029616       1
4  123123123123169  126395888234936       1

In [15]:
train_part1 = train_part1.merge(labels, how='left', on=['customer_id', 'event_id'])

In [16]:
train_part1["target"].value_counts(dropna=False)

target
NaN    28589128
1.0       17384
0.0       12082
Name: count, dtype: int64

In [17]:
###########
train_part1["target"] = train_part1["target"].fillna(0, inplace=True).astype(dtype="int16")

/tmp/ipykernel_11307/3661410496.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  train_part1["target"] = train_part1["target"].fillna(0, inplace=True).astype(dtype="int16")

In [18]:
train_part1

,customer_id,event_id,event_type_nm,event_desc,channel_indicator_type,channel_indicator_sub_type,operaton_amt,currency_iso_cd,mcc_code,pos_cd,...,operating_system_type,battery,device_system_version,screen_size,developer_tools,phone_voip_call_state,web_rdp_connection,compromised,Hour,target
0,123123123123129,123999300382879,14,75,6,5,56422.0,0.0,4,3.0,...,-1.0,-1,-1,-1,-1,-1,-1,-1,5,0
1,123123123123129,124531875713936,7,56,4,15,-1.0,-1.0,-1,-1.0,...,-1.0,-1,-1,-1,-1,-1,-1,-1,10,0
2,123123123123129,123329285580171,3,120,6,5,300870.0,0.0,10,3.0,...,-1.0,-1,-1,-1,-1,-1,-1,-1,10,0
3,123123123123129,124334305430665,14,75,6,5,298458.0,0.0,1,3.0,...,-1.0,-1,-1,-1,-1,-1,-1,-1,7,0
4,123123123123129,126215501146513,14,75,6,5,59944.0,0.0,15,3.0,...,-1.0,-1,-1,-1,-1,-1,-1,-1,11,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28618589,123501080247591,126490381958304,14,75,0,5,8067.0,0.0,4,-1.0,...,-1.0,-1,-1,-1,-1,-1,-1,-1,4,0
28618590,123501080247591,124128146411089,14,75,0,5,9005.0,0.0,4,-1.0,...,-1.0,-1,-1,-1,-1,-1,-1,-1,8,0
28618591,123501080247591,125433819853542,14,75,0,5,7992.0,0.0,4,-1.0,...,-1.0,-1,-1,-1,-1,-1,-1,-1,8,0
28618592,123501080247591,126215503301577,14,75,0,5,40849.0,0.0,4,-1.0,...,-1.0,-1,-1,-1,-1,-1,-1,-1,12,0
28618593,123501080247591,126052293072084,14,75,0,5,17487.0,0.0,4,-1.0,...,-1.0,-1,-1,-1,-1,-1,-1,-1,12,0

In [19]:
train_part1["target"].value_counts()

target
0    28601210
1       17384
Name: count, dtype: int64

In [20]:
train_part1.drop(columns=["customer_id", "event_id"], inplace=True)

In [21]:
train_part1

,event_type_nm,event_desc,channel_indicator_type,channel_indicator_sub_type,operaton_amt,currency_iso_cd,mcc_code,pos_cd,accept_language,browser_language,...,operating_system_type,battery,device_system_version,screen_size,developer_tools,phone_voip_call_state,web_rdp_connection,compromised,Hour,target
0,14,75,6,5,56422.0,0.0,4,3.0,-1,-1,...,-1.0,-1,-1,-1,-1,-1,-1,-1,5,0
1,7,56,4,15,-1.0,-1.0,-1,-1.0,-1,-1,...,-1.0,-1,-1,-1,-1,-1,-1,-1,10,0
2,3,120,6,5,300870.0,0.0,10,3.0,-1,-1,...,-1.0,-1,-1,-1,-1,-1,-1,-1,10,0
3,14,75,6,5,298458.0,0.0,1,3.0,-1,-1,...,-1.0,-1,-1,-1,-1,-1,-1,-1,7,0
4,14,75,6,5,59944.0,0.0,15,3.0,-1,-1,...,-1.0,-1,-1,-1,-1,-1,-1,-1,11,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28618589,14,75,0,5,8067.0,0.0,4,-1.0,-1,-1,...,-1.0,-1,-1,-1,-1,-1,-1,-1,4,0
28618590,14,75,0,5,9005.0,0.0,4,-1.0,-1,-1,...,-1.0,-1,-1,-1,-1,-1,-1,-1,8,0
28618591,14,75,0,5,7992.0,0.0,4,-1.0,-1,-1,...,-1.0,-1,-1,-1,-1,-1,-1,-1,8,0
28618592,14,75,0,5,40849.0,0.0,4,-1.0,-1,-1,...,-1.0,-1,-1,-1,-1,-1,-1,-1,12,0
28618593,14,75,0,5,17487.0,0.0,4,-1.0,-1,-1,...,-1.0,-1,-1,-1,-1,-1,-1,-1,12,0

In [22]:
train_part1["mcc_code"] = train_part1["mcc_code"].astype(dtype="int16")
train_part1["compromised"] = train_part1["compromised"].astype(dtype="int16")
train_part1["developer_tools"] = train_part1["developer_tools"].astype(dtype="int16")

In [23]:
train_part1.info()

<class 'pandas.DataFrame'>
RangeIndex: 28618594 entries, 0 to 28618593
Data columns (total 22 columns):
 #   Column                      Dtype
---  ------                      -----
 0   event_type_nm               int32
 1   event_desc                  int32
 2   channel_indicator_type      int32
 3   channel_indicator_sub_type  int32
 4   operaton_amt                float64
 5   currency_iso_cd             float64
 6   mcc_code                    int16
 7   pos_cd                      float64
 8   accept_language             object
 9   browser_language            object
 10  timezone                    float64
 11  session_id                  float64
 12  operating_system_type       float64
 13  battery                     object
 14  device_system_version       object
 15  screen_size                 object
 16  developer_tools             int16
 17  phone_voip_call_state       int16
 18  web_rdp_connection          int16
 19  compromised                 int16
 20  Hour                        int32
 21  target                      int16
dtypes: float64(6), int16(6), int32(5), object(5)
memory usage: 3.2+ GB

Сравню некоторые ранее удаленные столбцы для классов 0 и 1

In [27]:
train_part1.loc[train_part1["target"] == 1].tail(25)

,event_type_nm,event_desc,channel_indicator_type,channel_indicator_sub_type,operaton_amt,currency_iso_cd,mcc_code,pos_cd,accept_language,browser_language,...,operating_system_type,battery,device_system_version,screen_size,developer_tools,phone_voip_call_state,web_rdp_connection,compromised,Hour,target
17736894,9,37,4,14,29856000.0,0.0,-1,-1.0,-1,-1,...,-1.0,-1,-1,-1,-1,-1,-1,-1,10,1
17736895,7,56,4,15,-1.0,-1.0,-1,-1.0,-1,-1,...,-1.0,-1,14,1080x2176,0,0,-1,0,11,1
17736917,7,56,4,15,-1.0,-1.0,-1,-1.0,-1,-1,...,-1.0,-1,14,1080x2176,0,0,-1,0,9,1
17736926,7,56,4,15,-1.0,-1.0,-1,-1.0,-1,-1,...,-1.0,-1,14,1080x2176,0,0,-1,0,11,1
17736945,14,31,4,15,7992800.0,0.0,-1,-1.0,-1,-1,...,-1.0,-1,14,1080x2176,0,0,-1,0,16,1
17736950,14,36,4,15,422592.0,0.0,-1,-1.0,-1,-1,...,-1.0,-1,14,1080x2176,0,0,-1,0,16,1
17739037,7,56,4,15,-1.0,-1.0,-1,-1.0,-1,-1,...,-1.0,-1,10,1080x2060,0,0,-1,0,15,1
17739039,10,43,4,15,-1.0,-1.0,-1,-1.0,-1,-1,...,-1.0,-1,13,720x1436,0,1,-1,0,15,1
17742654,8,86,4,15,2090340.0,0.0,-1,-1.0,-1,-1,...,-1.0,-1,-1,-1,-1,-1,-1,0,14,1
17749028,7,56,4,15,-1.0,-1.0,-1,-1.0,-1,-1,...,-1.0,-1,12,720x1411,1,0,-1,0,16,1
17753895,14,75,0,5,19822.0,0.0,16,1.0,-1,-1,...,-1.0,-1,-1,-1,-1,-1,-1,-1,8,1
17754872,8,86,4,15,947245.0,0.0,-1,-1.0,-1,-1,...,-1.0,-1,13,1080x2194,0,0,-1,0,16,1
17754890,8,86,4,15,4455900.0,0.0,-1,-1.0,-1,-1,...,-1.0,-1,13,1080x2194,0,0,-1,0,17,1
17756159,14,75,0,5,43516.0,0.0,4,3.0,-1,-1,...,-1.0,-1,-1,-1,-1,-1,-1,-1,10,1
17756633,7,56,4,15,-1.0,-1.0,-1,-1.0,-1,-1,...,-1.0,-1,11,1080x2238,0,1,-1,0,11,1
17756642,2,88,0,5,-1.0,0.0,10,3.0,-1,-1,...,-1.0,-1,-1,-1,-1,-1,-1,-1,12,1
17756648,2,88,0,5,-1.0,0.0,10,3.0,-1,-1,...,-1.0,-1,-1,-1,-1,-1,-1,-1,12,1
17756652,3,120,0,5,19824000.0,0.0,10,3.0,-1,-1,...,-1.0,-1,-1,-1,-1,-1,-1,-1,12,1
17756655,2,88,0,5,-1.0,0.0,10,3.0,-1,-1,...,-1.0,-1,-1,-1,-1,-1,-1,-1,12,1
17756664,2,88,0,5,-1.0,0.0,10,3.0,-1,-1,...,-1.0,-1,-1,-1,-1,-1,-1,-1,12,1
17756668,2,88,0,5,-1.0,0.0,10,3.0,-1,-1,...,-1.0,-1,-1,-1,-1,-1,-1,-1,13,1
17758860,3,120,0,2,100770.0,0.0,10,8.0,-1,-1,...,-1.0,-1,-1,-1,-1,-1,-1,-1,15,1
17760597,14,75,0,5,50030.0,0.0,16,-1.0,-1,-1,...,-1.0,-1,-1,-1,-1,-1,-1,-1,11,1
17765142,8,86,4,15,3982000.0,0.0,-1,-1.0,-1,-1,...,-1.0,-1,14,1080x2249,1,-1,-1,0,15,1
17768197,7,56,4,15,-1.0,-1.0,-1,-1.0,-1,-1,...,-1.0,-1,14,1080x2262,0,-1,-1,0,9,1

In [49]:
train_part1["browser_language"].loc[train_part1["target"] == 1].unique()

array([-1, 'not available'], dtype=object)

In [50]:
train_part1["browser_language"].loc[train_part1["target"] == 0].unique()

array([-1, 'not available',
       ':not available,iframed:false,intip:2abb1272-fbd8-4d35-897d-b0ee3e862cfd.local,battery:0%,User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,reducedMotion:false,mouseTimingV1:[[2.772588722239781,2.833213344056216,5.484960471420001,3.38368026142383,1.3704421636579194]],userAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,webdriver:false,language:ru-RU,colorDepth:24,deviceMemory:8,pixelRatio:1,hardwareConcurrency:4,screenResolution:1920,1080,availableScreenResolution:1920,1040,timezoneOffset:-180,timezone:Europe/Moscow,sessionStorage:true,localStorage:true,indexedDb:true,openDatabase:false,platform:Win32,plugins:Adobe Acrobat,Adobe PDF Plug-In For Firefox and Netscape 24.5.20399,application/pdf,pdf,application/vnd.adobe.pdfxml,pdfxml,application/vnd.adobe.x-mars,mars,application/vnd.fdf,fdf,application/vnd.adobe.xfdf,xfdf,application/vnd.adobe.xdp+xml,xdp,application/vnd.adobe.xfd+xml,xfd,Alipay Security Control 3,Alipay Security Control,application/x-alisecctrl-plugin,*,Alipay security control,npaliedit,application/aliedit,,Chromium PDF Plugin,Portable Document Format,application/x-google-chrome-pdf,pdf,Chromium PDF Viewer,,application/pdf,pdf,Microsoft Office 2016,The plugin allows you to have a better experience with Microsoft SharePoint,application/x-sharepoint,,application/x-sharepoint-uc,,Microsoft® Windows Media Player Firefox Plugin,np-mswmp,application/x-ms-wmp,*,application/asx,*,video/x-ms-asf-plugin,*,application/x-mplayer2,*,video/x-ms-asf,asf,asx,*,video/x-ms-wm,wm,*,audio/x-ms-wma,wma,*,audio/x-ms-wax,wax,*,video/x-ms-wmv,wmv,*,video/x-ms-wvx,wvx,*,iTrusChina iTrusPTA,XEnroll,iEnroll,hwPTA,UKeyInstalls Firefox Plugin,iTrusPTA',
       ':not available,iframed:false,intip:f6a11e64-39dc-4cc8-bd07-ebdb764be5fd.local,battery:100%,User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,reducedMotion:false,mouseTimingV1:[[2.772588722239781,2.833213344056216,2.833213344056216,2.9058899974175274,0.4128512054517482],[2.772588722239781,2.833213344056216,3.6050398140853943,3.136713203893845,1.1954089692217564],[2.7058230259275198,2.833213344056216,4.211551134008321,3.1557078927149895,0.7981887381425107]],userAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,webdriver:false,language:ru-RU,colorDepth:24,deviceMemory:4,pixelRatio:1,hardwareConcurrency:8,screenResolution:900,1440,availableScreenResolution:860,1440,timezoneOffset:-180,timezone:Europe/Moscow,sessionStorage:true,localStorage:true,indexedDb:true,openDatabase:false,platform:Win32,plugins:Alipay Security Control 3,Alipay Security Control,application/x-alisecctrl-plugin,*,Alipay security control,npaliedit,application/aliedit,,Chromium PDF Plugin,Portable Document Format,application/x-google-chrome-pdf,pdf,Chromium PDF Viewer,,application/pdf,pdf,CryptoPro CAdES NPAPI Browser Plug-in,CryptoPro CAdES NPAPI Browser Plug-in,application/x-cades,,Microsoft® Windows Media Player Firefox Plugin,np-mswmp,application/x-ms-wmp,*,application/asx,*,video/x-ms-asf-plugin,*,application/x-mplayer2,*,video/x-ms-asf,asf,asx,*,video/x-ms-wm,wm,*,audio/x-ms-wma,wma,*,audio/x-ms-wax,wax,*,video/x-ms-wmv,wmv,*,video/x-ms-wvx,wvx,*,Shockwave Flash,Shockwave Flash 32.0 r0,application/x-shockwave-flash,swf,application/futuresplash,spl,iTrusChina iTrusPTA,XEnroll,iEnroll,hwPTA,UKeyInstalls Firefox Plugin,iTrusPTA',
       ':not available,iframed:false,intip:1ea3a92f-c7ea-4305-9723-3fb418ed1df4.local,battery:100%,User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,reducedMotion:false,mouseTimingV1:[[2.772588722239781,2.833213344056216,2.833213344056216,2.8421159104939644,0.14389368590311588],[2.772588722239781,2.833213344056216,3.337280695907213,2.9510307495766006,0.5279652647041363],[2.772588722239781,2.833213344056216,3.836611560560854,3.0496050788346,0.7159712071442551]],userAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,webdriver:false,language:ru-RU,colorDepth:24,deviceMemory:4,pixelRatio:1,hardwareConcurrency:8,screenResolution:900,1440,availableScreenResolution:860,1440,timezoneOffset:-180,timezone:Europe/Moscow,sessionStorage:true,localStorage:true,indexedDb:true,openDatabase:false,platform:Win32,plugins:Alipay Security Control 3,Alipay Security Control,application/x-alisecctrl-plugin,*,Alipay security control,npaliedit,application/aliedit,,Chromium PDF Plugin,Portable Document Format,application/x-google-chrome-pdf,pdf,Chromium PDF Viewer,,application/pdf,pdf,CryptoPro CAdES NPAPI Browser Plug-in,CryptoPro CAdES NPAPI Browser Plug-in,application/x-cades,,Microsoft® Windows Media Player Firefox Plugin,np-mswmp,application/x-ms-wmp,*,application/asx,*,video/x-ms-asf-plugin,*,application/x-mplayer2,*,video/x-ms-asf,asf,asx,*,video/x-ms-wm,wm,*,audio/x-ms-wma,wma,*,audio/x-ms-wax,wax,*,video/x-ms-wmv,wmv,*,video/x-ms-wvx,wvx,*,Shockwave Flash,Shockwave Flash 32.0 r0,application/x-shockwave-flash,swf,application/futuresplash,spl,iTrusChina iTrusPTA,XEnroll,iEnroll,hwPTA,UKeyInstalls Firefox Plugin,iTrusPTA',
       ':not available,systemLanguage:not available,userLanguage:not available,iframed:false,intip:fe560469-529d-4452-aad8-9cd9936f0751.local,battery:100%,reducedMotion:false,mouseTimingV1:[],userAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,webdriver:false,language:ru-RU,colorDepth:24,deviceMemory:8,pixelRatio:1,hardwareConcurrency:4,screenResolution:900,1600,availableScreenResolution:860,1600,timezoneOffset:-180,timezone:Europe/Moscow,sessionStorage:true,localStorage:true,indexedDb:true,addBehavior:false,openDatabase:false,cpuClass:not available,platform:Win32,plugins:Alipay Security Control 3,Alipay Security Control,application/x-alisecctrl-plugin,*,Alipay security control,npaliedit,application/aliedit,,Chromium PDF Plugin,Portable Document Format,application/x-google-chrome-pdf,pdf,Chromium PDF Viewer,,application/pdf,pdf,Microsoft Office,The plugin allows you to have a better experience with Microsoft SharePoint,application/x-sharepoint,,application/x-sharepoint-uc,,Microsoft® Windows Media Player Firefox Plugin,np-mswmp,application/x-ms-wmp,*,application/asx,*,video/x-ms-asf-plugin,*,application/x-mplayer2,*,video/x-ms-asf,asf,asx,*,video/x-ms-wm,wm,*,audio/x-ms-wma,wma,*,audio/x-ms-wax,wax,*,video/x-ms-wmv,wmv,*,video/x-ms-wvx,wvx,*,PDF-XChangeВ® Editor,PDF-XChange Editor Netscape Gecko Plugin,application/pdf,pdf,application/vnd.fdf,fdf,application/vnd.adobe.xfdf,xfdf,PDF-XChangeВ® Editor,PDF-XChange Editor Netscape Gecko Plugin,application/pdf,pdf,application/vnd.fdf,fdf,application/vnd.adobe.xfdf,xfdf,Shockwave Flash,Shockwave Flash 32.0 r0,application/x-shockwave-flash,swf,application/futuresplash,spl,Shockwave Flash,Shockwave Flash 32.0 r0,application/x-shockwave-flash,swf,application/futuresplash,spl,iTrusChina iTrusPTA,XEnroll,iEnroll,hwPTA,UKeyInstalls Firefox Plugin,iTrusPTA',
       ':not available,systemLanguage:not available,userLanguage:not available,iframed:false,intip:e324e321-1464-40d7-af4e-02aad15e23c7.local,battery:100%,reducedMotion:false,mouseTimingV1:[],userAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,webdriver:false,language:ru-RU,colorDepth:24,deviceMemory:8,pixelRatio:1,hardwareConcurrency:4,screenResolution:900,1600,availableScreenResolution:860,1600,timezoneOffset:-180,timezone:Europe/Moscow,sessionStorage:true,localStorage:true,indexedDb:true,addBehavior:false,openDatabase:false,cpuClass:not available,platform:Win32,plugins:Alipay Security Control 3,Alipay Security Control,application/x-alisecctrl-plugin,*,Alipay security control,npaliedit,application/aliedit,,Chromium PDF Plugin,Portable Document Format,application/x-google-chrome-pdf,pdf,Chromium PDF Viewer,,application/pdf,pdf,Microsoft Office,The plugin allows you to have a better experience with Microsoft SharePoint,application/x-sharepoint,,application/x-sharepoint-uc,,Microsoft® Windows Media Player Firefox Plugin,np-mswmp,application/x-ms-wmp,*,application/asx,*,video/x-ms-asf-plugin,*,application/x-mplayer2,*,video/x-ms-asf,asf,asx,*,video/x-ms-wm,wm,*,audio/x-ms-wma,wma,*,audio/x-ms-wax,wax,*,video/x-ms-wmv,wmv,*,video/x-ms-wvx,wvx,*,PDF-XChangeВ® Editor,PDF-XChange Editor Netscape Gecko Plugin,application/pdf,pdf,application/vnd.fdf,fdf,application/vnd.adobe.xfdf,xfdf,PDF-XChangeВ® Editor,PDF-XChange Editor Netscape Gecko Plugin,application/pdf,pdf,application/vnd.fdf,fdf,application/vnd.adobe.xfdf,xfdf,Shockwave Flash,Shockwave Flash 32.0 r0,application/x-shockwave-flash,swf,application/futuresplash,spl,Shockwave Flash,Shockwave Flash 32.0 r0,application/x-shockwave-flash,swf,application/futuresplash,spl,iTrusChina iTrusPTA,XEnroll,iEnroll,hwPTA,UKeyInstalls Firefox Plugin,iTrusPTA',
       ':not available,systemLanguage:not available,userLanguage:not available,iframed:false,intip:7ee7c8b4-f9eb-467d-8c8b-57d14f5a565b.local,battery:100%,reducedMotion:false,mouseTimingV1:[],userAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,webdriver:false,language:ru-RU,colorDepth:24,deviceMemory:8,pixelRatio:1,hardwareConcurrency:4,screenResolution:900,1600,availableScreenResolution:860,1600,timezoneOffset:-180,timezone:Europe/Moscow,sessionStorage:true,localStorage:true,indexedDb:true,addBehavior:false,openDatabase:false,cpuClass:not available,platform:Win32,plugins:Alipay Security Control 3,Alipay Security Control,application/x-alisecctrl-plugin,*,Alipay security control,npaliedit,application/aliedit,,Chromium PDF Plugin,Portable Document Format,application/x-google-chrome-pdf,pdf,Chromium PDF Viewer,,application/pdf,pdf,Microsoft Office,The plugin allows you to have a better experience with Microsoft SharePoint,application/x-sharepoint,,application/x-sharepoint-uc,,Microsoft® Windows Media Player Firefox Plugin,np-mswmp,application/x-ms-wmp,*,application/asx,*,video/x-ms-asf-plugin,*,application/x-mplayer2,*,video/x-ms-asf,asf,asx,*,video/x-ms-wm,wm,*,audio/x-ms-wma,wma,*,audio/x-ms-wax,wax,*,video/x-ms-wmv,wmv,*,video/x-ms-wvx,wvx,*,PDF-XChangeВ® Editor,PDF-XChange Editor Netscape Gecko Plugin,application/pdf,pdf,application/vnd.fdf,fdf,application/vnd.adobe.xfdf,xfdf,PDF-XChangeВ® Editor,PDF-XChange Editor Netscape Gecko Plugin,application/pdf,pdf,application/vnd.fdf,fdf,application/vnd.adobe.xfdf,xfdf,Shockwave Flash,Shockwave Flash 32.0 r0,application/x-shockwave-flash,swf,application/futuresplash,spl,Shockwave Flash,Shockwave Flash 32.0 r0,application/x-shockwave-flash,swf,application/futuresplash,spl,iTrusChina iTrusPTA,XEnroll,iEnroll,hwPTA,UKeyInstalls Firefox Plugin,iTrusPTA',
       ':not available,systemLanguage:not available,userLanguage:not available,iframed:false,intip:70060f7b-d0ae-42bc-b408-2c76ceb7bd98.local,battery:100%,reducedMotion:false,mouseTimingV1:[],userAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,webdriver:false,language:ru-RU,colorDepth:24,deviceMemory:8,pixelRatio:1,hardwareConcurrency:4,screenResolution:900,1600,availableScreenResolution:860,1600,timezoneOffset:-180,timezone:Europe/Moscow,sessionStorage:true,localStorage:true,indexedDb:true,addBehavior:false,openDatabase:false,cpuClass:not available,platform:Win32,plugins:Alipay Security Control 3,Alipay Security Control,application/x-alisecctrl-plugin,*,Alipay security control,npaliedit,application/aliedit,,Chromium PDF Plugin,Portable Document Format,application/x-google-chrome-pdf,pdf,Chromium PDF Viewer,,application/pdf,pdf,Microsoft Office,The plugin allows you to have a better experience with Microsoft SharePoint,application/x-sharepoint,,application/x-sharepoint-uc,,Microsoft® Windows Media Player Firefox Plugin,np-mswmp,application/x-ms-wmp,*,application/asx,*,video/x-ms-asf-plugin,*,application/x-mplayer2,*,video/x-ms-asf,asf,asx,*,video/x-ms-wm,wm,*,audio/x-ms-wma,wma,*,audio/x-ms-wax,wax,*,video/x-ms-wmv,wmv,*,video/x-ms-wvx,wvx,*,PDF-XChangeВ® Editor,PDF-XChange Editor Netscape Gecko Plugin,application/pdf,pdf,application/vnd.fdf,fdf,application/vnd.adobe.xfdf,xfdf,PDF-XChangeВ® Editor,PDF-XChange Editor Netscape Gecko Plugin,application/pdf,pdf,application/vnd.fdf,fdf,application/vnd.adobe.xfdf,xfdf,Shockwave Flash,Shockwave Flash 32.0 r0,application/x-shockwave-flash,swf,application/futuresplash,spl,Shockwave Flash,Shockwave Flash 32.0 r0,application/x-shockwave-flash,swf,application/futuresplash,spl,iTrusChina iTrusPTA,XEnroll,iEnroll,hwPTA,UKeyInstalls Firefox Plugin,iTrusPTA',
       ':not available,systemLanguage:not available,userLanguage:not available,iframed:false,intip:945012c0-54bc-44e5-9194-e73f30281068.local,battery:100%,reducedMotion:false,mouseTimingV1:[],userAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,webdriver:false,language:ru-RU,colorDepth:24,deviceMemory:8,pixelRatio:1,hardwareConcurrency:4,screenResolution:900,1600,availableScreenResolution:860,1600,timezoneOffset:-180,timezone:Europe/Moscow,sessionStorage:true,localStorage:true,indexedDb:true,addBehavior:false,openDatabase:false,cpuClass:not available,platform:Win32,plugins:Alipay Security Control 3,Alipay Security Control,application/x-alisecctrl-plugin,*,Alipay security control,npaliedit,application/aliedit,,Chromium PDF Plugin,Portable Document Format,application/x-google-chrome-pdf,pdf,Chromium PDF Viewer,,application/pdf,pdf,Microsoft Office,The plugin allows you to have a better experience with Microsoft SharePoint,application/x-sharepoint,,application/x-sharepoint-uc,,Microsoft® Windows Media Player Firefox Plugin,np-mswmp,application/x-ms-wmp,*,application/asx,*,video/x-ms-asf-plugin,*,application/x-mplayer2,*,video/x-ms-asf,asf,asx,*,video/x-ms-wm,wm,*,audio/x-ms-wma,wma,*,audio/x-ms-wax,wax,*,video/x-ms-wmv,wmv,*,video/x-ms-wvx,wvx,*,PDF-XChangeВ® Editor,PDF-XChange Editor Netscape Gecko Plugin,application/pdf,pdf,application/vnd.fdf,fdf,application/vnd.adobe.xfdf,xfdf,PDF-XChangeВ® Editor,PDF-XChange Editor Netscape Gecko Plugin,application/pdf,pdf,application/vnd.fdf,fdf,application/vnd.adobe.xfdf,xfdf,Shockwave Flash,Shockwave Flash 32.0 r0,application/x-shockwave-flash,swf,application/futuresplash,spl,Shockwave Flash,Shockwave Flash 32.0 r0,application/x-shockwave-flash,swf,application/futuresplash,spl,iTrusChina iTrusPTA,XEnroll,iEnroll,hwPTA,UKeyInstalls Firefox Plugin,iTrusPTA',
       ':not available,iframed:false,intip:4b264c4c-6462-4af7-b1de-b7c494103fba.local,battery:100%,User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,reducedMotion:false,mouseTimingV1:[],userAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,webdriver:false,language:ru-RU,colorDepth:24,deviceMemory:8,pixelRatio:1,hardwareConcurrency:4,screenResolution:900,1600,availableScreenResolution:860,1600,timezoneOffset:-180,timezone:Europe/Moscow,sessionStorage:true,localStorage:true,indexedDb:true,openDatabase:false,platform:Win32,plugins:Alipay Security Control 3,Alipay Security Control,application/x-alisecctrl-plugin,*,Alipay security control,npaliedit,application/aliedit,,Chromium PDF Plugin,Portable Document Format,application/x-google-chrome-pdf,pdf,Chromium PDF Viewer,,application/pdf,pdf,Microsoft Office,The plugin allows you to have a better experience with Microsoft SharePoint,application/x-sharepoint,,application/x-sharepoint-uc,,Microsoft® Windows Media Player Firefox Plugin,np-mswmp,application/x-ms-wmp,*,application/asx,*,video/x-ms-asf-plugin,*,application/x-mplayer2,*,video/x-ms-asf,asf,asx,*,video/x-ms-wm,wm,*,audio/x-ms-wma,wma,*,audio/x-ms-wax,wax,*,video/x-ms-wmv,wmv,*,video/x-ms-wvx,wvx,*,PDF-XChangeВ® Editor,PDF-XChange Editor Netscape Gecko Plugin,application/pdf,pdf,application/vnd.fdf,fdf,application/vnd.adobe.xfdf,xfdf,PDF-XChangeВ® Editor,PDF-XChange Editor Netscape Gecko Plugin,application/pdf,pdf,application/vnd.fdf,fdf,application/vnd.adobe.xfdf,xfdf,Shockwave Flash,Shockwave Flash 32.0 r0,application/x-shockwave-flash,swf,application/futuresplash,spl,Shockwave Flash,Shockwave Flash 32.0 r0,application/x-shockwave-flash,swf,application/futuresplash,spl,iTrusChina iTrusPTA,XEnroll,iEnroll,hwPTA,UKeyInstalls Firefox Plugin,iTrusPTA',
       ':not available,iframed:false,intip:7e8d1c01-a28b-4925-985a-75bfd8214657.local,battery:100%,User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,reducedMotion:false,mouseTimingV1:[[2.70805020110221,2.833213344056216,3.4811217321331034,2.9410721418523376,0.2736365524791759]],userAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,webdriver:false,language:ru-RU,colorDepth:24,deviceMemory:8,pixelRatio:1,hardwareConcurrency:4,screenResolution:900,1600,availableScreenResolution:860,1600,timezoneOffset:-180,timezone:Europe/Moscow,sessionStorage:true,localStorage:true,indexedDb:true,openDatabase:false,platform:Win32,plugins:Alipay Security Control 3,Alipay Security Control,application/x-alisecctrl-plugin,*,Alipay security control,npaliedit,application/aliedit,,Chromium PDF Plugin,Portable Document Format,application/x-google-chrome-pdf,pdf,Chromium PDF Viewer,,application/pdf,pdf,Microsoft Office,The plugin allows you to have a better experience with Microsoft SharePoint,application/x-sharepoint,,application/x-sharepoint-uc,,Microsoft® Windows Media Player Firefox Plugin,np-mswmp,application/x-ms-wmp,*,application/asx,*,video/x-ms-asf-plugin,*,application/x-mplayer2,*,video/x-ms-asf,asf,asx,*,video/x-ms-wm,wm,*,audio/x-ms-wma,wma,*,audio/x-ms-wax,wax,*,video/x-ms-wmv,wmv,*,video/x-ms-wvx,wvx,*,PDF-XChangeВ® Editor,PDF-XChange Editor Netscape Gecko Plugin,application/pdf,pdf,application/vnd.fdf,fdf,application/vnd.adobe.xfdf,xfdf,PDF-XChangeВ® Editor,PDF-XChange Editor Netscape Gecko Plugin,application/pdf,pdf,application/vnd.fdf,fdf,application/vnd.adobe.xfdf,xfdf,Shockwave Flash,Shockwave Flash 32.0 r0,application/x-shockwave-flash,swf,application/futuresplash,spl,Shockwave Flash,Shockwave Flash 32.0 r0,application/x-shockwave-flash,swf,application/futuresplash,spl,iTrusChina iTrusPTA,XEnroll,iEnroll,hwPTA,UKeyInstalls Firefox Plugin,iTrusPTA',

In [47]:
train_part1["accept_language"].loc[train_part1["target"] == 1].unique()

array([-1, 'ru', '*', 'ru-ru', 'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7',
       'en-GB,en;q=0.9', 'ru-ua',
       'ru,uk-UA;q=0.9,uk;q=0.8,en-US;q=0.7,en;q=0.6', 'ru,en;q=0.9',
       'uk-ua', 'ru-us', 'fr-FR,fr;q=0.8,en-US;q=0.5,en;q=0.3',
       'be-BY,be;q=0.9,en-US;q=0.8,en;q=0.7',
       'ru-RU,ru;q=0.9,ka-GE;q=0.8,ka;q=0.7,en-US;q=0.6,en;q=0.5',
       'en-US,en;q=0.9', 'en-us', 'en-gb',
       'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3', 'az-az',
       'ru,en;q=0.9,en-GB;q=0.8,en-US;q=0.7', 'ru,en;q=0.9,tg;q=0.8',
       'ja', 'tr-TR,tr;q=0.9', 'zh-tw',
       'pt-PT,pt;q=0.9,en-US;q=0.8,en;q=0.7,ru;q=0.6,fi;q=0.5'],
      dtype=object)

In [48]:
train_part1["accept_language"].loc[train_part1["target"] == 0].unique()

array([-1, 'ru-ru', 'ru', 'ru,en;q=0.9',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7', '*',
       'ru,en;q=0.9,en-GB;q=0.8,en-US;q=0.7',
       'ru,uk-UA;q=0.9,uk;q=0.8,en-US;q=0.7,en;q=0.6', 'en-GB,en;q=0.9',
       'en-gb', 'ru-RU,ru;q=0.9,en-us;q=0.8,en;q=0.7',
       'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3', 'ru-RU,ru;q=0.9',
       'ru,en;q=0.9,en-GB;q=0.8,en-US;q=0.7,fi;q=0.6', 'en,ru;q=0.9',
       'en', 'ru,en-US;q=0.7,en;q=0.3', 'en-us', 'ru-RU',
       'ru,en;q=0.9,de;q=0.8', 'ru,ru-RU;q=0.9,en-US;q=0.8,en;q=0.7',
       'ru-RU,ru;q=0.9,en-IN;q=0.8,en-US;q=0.7,en;q=0.6',
       'ru,en;q=0.9,uk;q=0.8',
       'ru-RU,ru;q=0.9,el-CY;q=0.8,el;q=0.7,en-US;q=0.6,en;q=0.5',
       'en-US,en;q=0.9',
       'ru-RU,ru;q=0.9,en-IN;q=0.8,en;q=0.7,en-US;q=0.6',
       'ru-RU,ru;q=0.9,en-AS;q=0.8,en-US;q=0.7,en;q=0.6',
       'ru-RU,ru;q=0.9,en-AU;q=0.8,en;q=0.7,en-US;q=0.6',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,bg;q=0.6,es;q=0.5', 'ru-ua',
       'tr-tr',
       'ru-RU,ru;q=0.9,es-RU;q=0.8,es;q=0.7,en-US;q=0.6,en;q=0.5',
       'ru,en;q=0.9,en-GB;q=0.8,en-US;q=0.7,zh-TW;q=0.6,zh;q=0.5',
       'en-US,en;q=0.9,ru-RU;q=0.8,ru;q=0.7', 'ru,en-US;q=0.9,en;q=0.8',
       'ru-RU,en-US;q=0.9', 'de,en-US;q=0.9,en;q=0.8,ru;q=0.7',
       'en,ru;q=0.9,en-GB;q=0.8,en-US;q=0.7',
       'en-US,en;q=0.9,ru;q=0.8,id;q=0.7,es;q=0.6',
       'ru,en;q=0.9,be;q=0.8',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,bg;q=0.6',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6,zh;q=0.5',
       'ru,en;q=0.9,is;q=0.8',
       'ru-RU,ru;q=0.9,de-DE;q=0.8,de;q=0.7,es-ES;q=0.6,es;q=0.5,en-GB;q=0.4,en;q=0.3,fr-FR;q=0.2,fr;q=0.1,pl-PL;q=0.1,pl;q=0.1,it-IT;q=0.1,it;q=0.1,en-US;q=0.1',
       'en-np', 'ru,en-US;q=0.9,en;q=0.8,az;q=0.7',
       'ru-RU,ru;q=0.9,uk-UA;q=0.8,uk;q=0.7,en-US;q=0.6,en;q=0.5',
       'ru-US,ru;q=0.9,en-US;q=0.8,en;q=0.7,ru-RU;q=0.6',
       'ru,ru-RU;q=0.9,en-US;q=0.8,en;q=0.7,mk;q=0.6', 'ru-RU,ru;q=0.7',
       'ru,en;q=0.9,en-US;q=0.8', 'en-US,en;q=0.9,ru;q=0.8',
       'de-DE,de;q=0.9', 'de-de',
       'de,ru-RU;q=0.9,ru;q=0.8,en-US;q=0.7,en;q=0.6',
       'ru-RU,ru;q=0.9,en;q=0.8',
       'ru-RU,ru;q=0.9,de-DE;q=0.8,de;q=0.7,en-US;q=0.6,en;q=0.5',
       'ru,en;q=0.9,ru-RU;q=0.8,en-RU;q=0.7,ru-AU;q=0.6,en-US;q=0.5',
       'ru,en;q=0.9,es;q=0.8,mt;q=0.7,uk;q=0.6', 'ru,en;q=0.9,bg;q=0.8',
       'uk-UA,uk;q=0.9', 'uk-ua',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,de;q=0.6',
       'ru,en-US;q=0.9,en;q=0.8,kk;q=0.7', 'en-US,en;q=0.5', 'ru-us',
       'fr-FR,fr;q=0.8,en-US;q=0.5,en;q=0.3',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,vi;q=0.6',
       'ru-RU,ru;q=0.9,kk-KZ;q=0.8,kk;q=0.7,en-US;q=0.6,en;q=0.5',
       'en-GB,en;q=0.9,ru-RU;q=0.8,ru;q=0.7,en-US;q=0.6',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,bn;q=0.6,bg;q=0.5',
       'ru-RU,ru;q=0.9,en-GB;q=0.8,en;q=0.7,en-US;q=0.6', 'ru-gb',
       'ru,en;q=0.9,zh-CN;q=0.8,zh;q=0.7,en-GB;q=0.6,en-US;q=0.5',
       'ru,en;q=0.9,en-GB;q=0.8,en-US;q=0.7,de;q=0.6',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,el;q=0.6', 'ru-ai',
       'ru,de;q=0.9,en;q=0.8,en-US;q=0.7,nb;q=0.6,be;q=0.5',
       'ru,en;q=0.9,bg;q=0.8,fr;q=0.7,it;q=0.6,de;q=0.5',
       'zh-CN,zh-Hans;q=0.9', 'zh-cn',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,uk;q=0.6,und;q=0.5,de;q=0.4',
       'ru,en;q=0.9,uk;q=0.8,es;q=0.7',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,zh-TW;q=0.6,zh;q=0.5,ka;q=0.4',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,fr;q=0.6',
       'ru,en;q=0.9,tt;q=0.8',
       'ru-RU,ru;q=0.9,zh-CN;q=0.8,zh;q=0.7,be-RU;q=0.6,be;q=0.5,en-US;q=0.4,en;q=0.3',
       'ru-RU,ru;q=0.9,en-AI;q=0.8,en-US;q=0.7,en;q=0.6',
       'ru-KZ,ru-RU;q=0.9,ru;q=0.8,en-US;q=0.7,en;q=0.6', 'ru-kz',
       'ru-RU,ru;q=0.9,de-DE;q=0.8,de;q=0.7,en-GB;q=0.6,en;q=0.5,es-IC;q=0.4,es;q=0.3,en-US;q=0.2',
       'ru,en;q=0.9,fr;q=0.8,it;q=0.7',
       'ru,en;q=0.9,fr;q=0.8,it;q=0.7,tr;q=0.6', 'be', 'be,ru;q=0.9',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,hy;q=0.6',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,zh-TW;q=0.6,zh;q=0.5', 'ja',
       'ja,en-US;q=0.9,en;q=0.8', 'en-US,de-DE;q=0.5',
       'ru,en;q=0.9,es;q=0.8', 'vi-vn', 'ru,en;q=0.9,vi;q=0.8',
       'ru,en;q=0.9,en-GB;q=0.8',
       'ru-BY,ru-RU;q=0.9,ru;q=0.8,en-US;q=0.7,en;q=0.6', 'ru-by',
       'ru,en;q=0.9,fr;q=0.8', 'ru-RU,ru;q=0.9,en;q=0.8,en-US;q=0.7',
       'ru-RU,ru;q=0.9,ka-GE;q=0.8,ka;q=0.7,en-US;q=0.6,en;q=0.5',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,uk;q=0.6,cs;q=0.5',
       'ru,en-US;q=0.9,en;q=0.8,uk;q=0.7,cs;q=0.6,nl;q=0.5',
       'ru,en;q=0.9,de;q=0.8,fr;q=0.7', 'ru,en;q=0.9,da;q=0.8',
       'ru,en-US;q=0.9,en;q=0.8,ko;q=0.7', 'en,ru;q=0.5',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,id;q=0.6',
       'ru-RU,ru;q=0.9,pl-PL;q=0.8,pl;q=0.7,en-US;q=0.6,en;q=0.5', 'pl',
       'pl,ru;q=0.9,en-US;q=0.8,en;q=0.7,de;q=0.6',
       'pl,ru;q=0.9,en-US;q=0.8,en;q=0.7,de;q=0.6,tr;q=0.5',
       'ru,ru-RU;q=0.9,en-US;q=0.8,en;q=0.7,pl;q=0.6',
       'ru,en;q=0.9,tr;q=0.8', 'it-it', 'ru,en;q=0.9,zh;q=0.8',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,lt;q=0.6',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,be;q=0.6',
       'en-US,en;q=0.9,ru;q=0.8,mt;q=0.7', 'zh-CN,zh;q=0.9',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,uz;q=0.6',
       'ru-RU,ru;q=0.9,tr-TR;q=0.8,tr;q=0.7,en-US;q=0.6,en;q=0.5',
       'uk-UA,uk;q=0.9,en-US;q=0.8,en;q=0.7',
       'ru-RU,ru;q=0.9,en-CA;q=0.8,en;q=0.7,en-US;q=0.6',
       'ru,uk;q=0.9,en;q=0.8', 'en-US,en;q=0.9,ru;q=0.8,de;q=0.7',
       'uz-UZ,uz;q=0.9,ru-RU;q=0.8,ru;q=0.7,en-US;q=0.6,en;q=0.5',
       'ru,en-US;q=0.9,en;q=0.8,tg;q=0.7',
       'en-US,en;q=0.9,ru;q=0.8,zh-CN;q=0.7,zh;q=0.6',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,ja;q=0.6',
       'fr-FR,fr;q=0.9,ru;q=0.8,en;q=0.7', 'fr-fr', 'fr-FR,fr;q=0.9',
       'ru-RU,ru;q=0.9,en-MM;q=0.8,en-US;q=0.7,en;q=0.6',
       'ru-RU,en-US;q=0.5',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,it;q=0.6,az;q=0.5',
       'ru,en;q=0.9,ky;q=0.8', 'ru,en-GB;q=0.9,en;q=0.8',
       'ru-RU,ru;q=0.6', 'ru-RU,ru;q=0.5', 'ru-RU,ru;q=0.8',
       'en-RU,en;q=0.9,ru-RU;q=0.8,ru;q=0.7,en-US;q=0.6',
       'ru-RU,ru;q=0.9,tg-TJ;q=0.8,tg;q=0.7,en-US;q=0.6,en;q=0.5',
       'ru-RU,ru;q=0.9,en-UM;q=0.8,en;q=0.7,en-US;q=0.6', 'sah,ru;q=0.9',
       'sah', 'ru-RU,ru-UA;q=0.9,ru;q=0.8,en-US;q=0.7,en;q=0.6',
       'ru,en;q=0.9,ko;q=0.8',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,tr;q=0.6', 'nb-NO,nb;q=0.9',
       'nb-no', 'en-GB,en-US;q=0.9,en;q=0.8',
       'ru,en-US;q=0.9,en;q=0.8,be;q=0.7', 'ru,en;q=0.9,mt;q=0.8',
       'hy,ru;q=0.9', 'ru,en-US;q=0.9,en;q=0.8,no;q=0.7,ja;q=0.6',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,zh-TW;q=0.6,zh;q=0.5,tr;q=0.4,es;q=0.3,af;q=0.2',
       'es-419', 'es-419,es;q=0.9', 'es-ES,es;q=0.9', 'es-es',
       'ru-RU,ru;q=0.9,en-HK;q=0.8,en;q=0.7,en-US;q=0.6',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,sr;q=0.6,hr;q=0.5',
       'ru-RU,ru;q=0.9,en-GB;q=0.8,en-US;q=0.7,en;q=0.6',
       'ru,en;q=0.9,de;q=0.8,zh;q=0.7,it;q=0.6',
       'ru,en-US;q=0.9,en;q=0.8,zh-CN;q=0.7,zh;q=0.6,zh-TW;q=0.5',
       'ru,en;q=0.9,ru-RU;q=0.8',
       'ru-RU,ru;q=0.9,en-CA;q=0.8,en;q=0.7,zh-CN;q=0.6,zh;q=0.5,en-US;q=0.4',
       'ru-AU,ru;q=0.9,en-US;q=0.8,en;q=0.7', 'ru-au', 'en-ca',
       'en-CA,en;q=0.9,ru-RU;q=0.8,ru;q=0.7,en-US;q=0.6',
       'ru-RU,ru;q=0.9,en-AS;q=0.8,en;q=0.7,en-US;q=0.6',
       'ru-RU,ru;q=0.9,ko-KR;q=0.8,ko;q=0.7,en-US;q=0.6,en;q=0.5',
       'ru,en-US;q=0.9,en;q=0.8,bg;q=0.7',
       'ru-RU,ru;q=0.9,zh-HK;q=0.8,zh;q=0.7,en-US;q=0.6,en;q=0.5',
       'ru-RU,ru;q=0.9,th-TH;q=0.8,th;q=0.7,en-US;q=0.6,en;q=0.5',
       'ru,en;q=0.9,es;q=0.8,tr;q=0.7,it;q=0.6,bg;q=0.5',
       'ru-RU,ru;q=0.9,de-DE;q=0.8,de;q=0.7,en-GB;q=0.6,en;q=0.5,en-US;q=0.4',
       'az-Cyrl,ru;q=0.9',
       'zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6',
       'ru,en;q=0.9,la;q=0.8', 'az-az',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,pl;q=0.6,de;q=0.5',
       'ru-AI,ru-RU;q=0.9,ru;q=0.8,en-US;q=0.7,en;q=0.6',
       'ru,en;q=0.9,cy;q=0.8', 'en-GB,en;q=0.9,en-US;q=0.8,ru;q=0.7',
       'ru,en-GB;q=0.9,en-US;q=0.8,en;q=0.7',
       'ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7,ru-RU;q=0.6,ru;q=0.5',
       'ru-RU,ru;q=0.9,tr-TR;q=0.8,tr;q=0.7,ko-KR;q=0.6,ko;q=0.5,en-US;q=0.4,en;q=0.3',
       'en-GB,en;q=0.9,en-US;q=0.8',
       'en-GB,en;q=0.9,en-US;q=0.8,uk;q=0.7,ru;q=0.6', 'en-US,en;q=0.6',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,uk;q=0.6,bg;q=0.5',
       'ru,en;q=0.9,uk;q=0.8,bg;q=0.7',
       'en,ru-RU;q=0.9,ru;q=0.8,en-US;q=0.7', 'ru,en;q=0.9,tg;q=0.8',
       'fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7,ru;q=0.6',
       'ru,en;q=0.9,it;q=0.8',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,ko;q=0.6,es;q=0.5',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,ar;q=0.6',
       'ru-AU,ru;q=0.9,kk-AU;q=0.8,kk;q=0.7,ru-RU;q=0.6,en-US;q=0.5,en;q=0.4',
       'en-CA,en-GB;q=0.9,en-US;q=0.8,en;q=0.7,ru;q=0.6',
       'ru,en;q=0.9,ja;q=0.8,ko;q=0.7,mk;q=0.6', 'vi-VN,vi;q=0.9',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,ja;q=0.6,es;q=0.5', 'ru-id',
       'ru-RU,ru;q=0.9,en;q=0.8,de;q=0.7',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,he;q=0.6',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,ja;q=0.6,zh-TW;q=0.5,zh-CN;q=0.4,zh;q=0.3',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,uk;q=0.6',
       'ru,en;q=0.9,de;q=0.8,es;q=0.7', 'ru-at',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,ceb;q=0.6',
       'ru,en;q=0.9,pt;q=0.8', 'tr-TR,tr;q=0.9',
       'ru,en-US;q=0.9,en;q=0.8,en-GB;q=0.7',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,ko;q=0.6',
       'en,en-US;q=0.9,ru;q=0.8', 'ru,en;q=0.9,ba;q=0.8',
       'ru,en;q=0.9,tr;q=0.8,sk;q=0.7', 'ru,ru-RU;q=0.9',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,it;q=0.6',
       'ru,en-US;q=0.9,en;q=0.8,zh-TW;q=0.7,zh;q=0.6,ko;q=0.5',
       'ru-RU,ru;q=0.9,en-AS;q=0.8,en;q=0.7,uz-UZ;q=0.6,uz;q=0.5,en-US;q=0.4',
       'en,en-US;q=0.9',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6,zh-TW;q=0.5,zh;q=0.4',
       'ru-RU,ru;q=0.9,en-GB;q=0.8,en;q=0.7,el-GR;q=0.6,el;q=0.5,en-US;q=0.4',
       'ru,en;q=0.9,fi;q=0.8',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,su;q=0.6',
       'ru,en-US;q=0.9,en;q=0.8,su;q=0.7,tg;q=0.6',
       'en-CA,en;q=0.9,ru;q=0.8,en-US;q=0.7,zh-TW;q=0.6,zh;q=0.5',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,ka;q=0.6',
       'zh-TW,zh-Hant;q=0.9', 'zh-tw',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,it;q=0.6,de;q=0.5',
       'ru,en-US;q=0.9,en;q=0.8,tr;q=0.7',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,kk;q=0.6',
       'ru,en-US;q=0.9,en;q=0.8,ru-RU;q=0.7',
       'ru,en-US;q=0.9,en;q=0.8,ny;q=0.7', 'sv-SE,sv;q=0.9',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,th;q=0.6',
       'ru-RU,ru;q=0.9,en-RU;q=0.8,en;q=0.7,en-US;q=0.6', 'en-nz',
       'en-US,en;q=0.9,ru;q=0.8,ru-RU;q=0.7',
       'ru-BO,ru;q=0.9,es-BO;q=0.8,es;q=0.7,en-US;q=0.6,en;q=0.5',
       'ru-RU,ru;q=0.9,uz-UZ;q=0.8,uz;q=0.7,en-US;q=0.6,en;q=0.5',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,tg;q=0.6',
       'en-GB,en;q=0.9,ru-RU;q=0.8,ru;q=0.7,en-US;q=0.6,es;q=0.5',
       'ru,en-US;q=0.9,en;q=0.8,uk;q=0.7',
       'ru,en-US;q=0.9,en;q=0.8,zh-CN;q=0.7,zh;q=0.6',
       'uk,ru;q=0.9,en;q=0.8',
       'ru,en;q=0.9,uk;q=0.8,it;q=0.7,ba;q=0.6,es;q=0.5,sk;q=0.4,tr;q=0.3,de;q=0.2,pl;q=0.1,cy;q=0.1,fi;q=0.1',
       'ru,en;q=0.9,en-GB;q=0.8,en-US;q=0.7,uk;q=0.6',
       'ru-RU,ru;q=0.9,en-AI;q=0.8,en;q=0.7,en-US;q=0.6',
       'ecdb8b444ca7fb7279ad262ebca14a18dc177e00',
       '1dc638f4b4f0110e082bb0f89d0ec6fe2fa7de83',
       'e2c8612bae6bdfe13f2df8afa593f0c3836cf6b2',
       '71121ccd559e78f44b1429e01b875f68f944bf4f',
       '74fb8830d4ad6b37558e1c78057d211ab507a182',
       'ru,en-GB;q=0.9,en;q=0.8,en-US;q=0.7', 'nl-nl',
       'ru-RU,ru;q=0.9,be-BY;q=0.8,be;q=0.7,en-US;q=0.6,en;q=0.5',
       'en-GB,en;q=0.9,ru;q=0.8', 'ru,en;q=0.9,mk;q=0.8',
       'ru,en-US;q=0.9,en;q=0.8,hy;q=0.7,sl;q=0.6',
       'ru-RU,ru;q=0.9,ro-RO;q=0.8,ro;q=0.7,pt-PT;q=0.6,pt;q=0.5,de-BE;q=0.4,de;q=0.3,en-US;q=0.2,en;q=0.1,id-ID;q=0.1,id;q=0.1',
       'en-GB,en-US;q=0.9,en;q=0.8,ru;q=0.7,nl;q=0.6',
       'en-GB,en-US;q=0.9,en;q=0.8,ru;q=0.7',
       'ru-RU,ru;q=0.9,en-RU;q=0.8,en-US;q=0.7,en;q=0.6',
       'en-US,en;q=0.9,si;q=0.8,ig;q=0.7,ru;q=0.6', 'et-ee',
       'et-EE,et;q=0.9,en-US;q=0.8,en;q=0.7',
       'it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7,ru;q=0.6,gd;q=0.5',
       'ru,en;q=0.9,de;q=0.8,tg;q=0.7,ba;q=0.6',
       'en-GB,en;q=0.9,ru;q=0.8,en-US;q=0.7',
       'pt-PT,pt;q=0.9,en-US;q=0.8,en;q=0.7,ru;q=0.6,fi;q=0.5', 'pt-pt',
       'ru,en;q=0.9,es;q=0.8,bg;q=0.7',
       'en-US,en;q=0.9,ru-RU;q=0.8,ru;q=0.7,de;q=0.6',
       'ru,en;q=0.9,pl;q=0.8',
       'de-DE,de;q=0.9,ru-RU;q=0.8,ru;q=0.7,en-US;q=0.6,en;q=0.5',
       'ru,en-US;q=0.9,en;q=0.8,fa;q=0.7',
       'ru,en-US;q=0.9,en;q=0.8,sq;q=0.7', 'en-GB,en-US;q=0.5',
       'en,ru;q=0.9,en-US;q=0.8,ru-RU;q=0.7,fi;q=0.6',
       'ru-ES,ru-RU;q=0.9,ru;q=0.8,en-US;q=0.7,en;q=0.6',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,ba;q=0.6',
       'ru-RU,ru;q=0.9,en-TZ;q=0.8,en;q=0.7,en-US;q=0.6', 'os,ru;q=0.9',
       'os', 'ru,en;q=0.9,fa;q=0.8',
       'ru,ru-RU;q=0.8,en-US;q=0.5,en;q=0.3',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,ro;q=0.6',
       'ru,ru-RU;q=0.9,en;q=0.8',
       'ru,en;q=0.9,ko;q=0.8,it;q=0.7,pt;q=0.6', 'ru-dk', 'uz-uz',
       'ru,en;q=0.5',
       'ru,en-US;q=0.9,en;q=0.8,it;q=0.7,de;q=0.6,es;q=0.5',
       'en,ru-RU;q=0.9,ru;q=0.8,en-GB;q=0.7,en-US;q=0.6', 'en-ru',
       'ru-RU,ru;q=0.9,en-CA;q=0.8,en-US;q=0.7,en;q=0.6',
       'ru-RU,ru;q=0.9,en-XA;q=0.8,en-US;q=0.7,en;q=0.6',
       'en-RU,en;q=0.9,ru-RU;q=0.8,ru;q=0.7,en-GB;q=0.6,en-US;q=0.5',
       '39a0131ee144d470e14a636b806e2464a7285172', 'ru-hk',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,ja;q=0.6,it;q=0.5',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,fi;q=0.6',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,vi;q=0.6,zh-CN;q=0.5,zh;q=0.4,ko;q=0.3,ja;q=0.2,es;q=0.1',
       'ru,en;q=0.9,nl;q=0.8',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,am;q=0.6',
       'en-RU,en-us;q=0.9,en;q=0.8', 'myv',
       'ru-IN,ru-RU;q=0.9,ru;q=0.8,en-US;q=0.7,en;q=0.6', 'ru-in',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,pl;q=0.6,da;q=0.5',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,es;q=0.6,ja;q=0.5,de;q=0.4,af;q=0.3',
       'ru-RU,ru;q=0.9,az-AZ;q=0.8,az;q=0.7,en-US;q=0.6,en;q=0.5',
       'ru-GB,ru;q=0.9,en-GB;q=0.8,en;q=0.7,ru-RU;q=0.6,en-US;q=0.5',
       'ru-GB,ru;q=0.9,en-RU;q=0.8,en;q=0.7,ru-RU;q=0.6,en-US;q=0.5',
       'zh-CN,zh;q=0.9,ru-RU;q=0.8,ru;q=0.7,en-US;q=0.6,en;q=0.5',
       'ru,en-US;q=0.9,en;q=0.8,lv;q=0.7,el;q=0.6',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,sv;q=0.6,da;q=0.5',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,bg;q=0.6,az;q=0.5,af;q=0.4,ak;q=0.3',
       'ru,en-US;q=0.9,en;q=0.8,ig;q=0.7', 'ru,cy;q=0.9',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,su;q=0.6,sr;q=0.5',
       'ru-RU,ru;q=0.9,fr-FR;q=0.8,fr;q=0.7,en-US;q=0.6,en;q=0.5',
       'ru-RU,ru;q=0.9,ar-EG;q=0.8,ar;q=0.7,en-US;q=0.6,en;q=0.5',
       'ru-RU,ru;q=0.9,en-AU;q=0.8,en-US;q=0.7,en;q=0.6',
       'ru-RU,ru;q=0.9,en;q=0.8,en-GB;q=0.7',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,zh-TW;q=0.6,zh-CN;q=0.5,zh;q=0.4',
       'ru,en;q=0.9,en-GB;q=0.8,en-US;q=0.7,ka;q=0.6',
       'ru,en;q=0.9,uk;q=0.8,ko;q=0.7',
       'ru-GB,ru;q=0.9,en-US;q=0.8,en;q=0.7',
       'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,de;q=0.6,it;q=0.5',
       'ru-MM,ru;q=0.9,en-RU;q=0.8,en;q=0.7,ru-RU;q=0.6,en-US;q=0.5',
       'ru-mm', 'ru,en-US;q=0.9,en;q=0.8,be;q=0.7,de-DE;q=0.6,de;q=0.5',
       'ru,en;q=0.9,hy;q=0.8',
       'vi-VN,vi;q=0.9,en-US;q=0.8,en;q=0.7,ru-RU;q=0.6,ru;q=0.5,fr-FR;q=0.4,fr;q=0.3',
       'th-TH,th;q=0.9', 'th-th', 'lo-la',
       'ru,en;q=0.9,zh;q=0.8,uk;q=0.7',
       'ru,ru-RU;q=0.9,en-US;q=0.8,en;q=0.7,de;q=0.6',
       'ru,en;q=0.9,ja;q=0.8,nb;q=0.7,zh;q=0.6', 'ru-RU,de-DE;q=0.5',
       'ru-RU,ru;q=0.9,ja-JP;q=0.8,ja;q=0.7,en-US;q=0.6,en;q=0.5',
       'ru,en;q=0.9,sr;q=0.8', 'ru,en-US;q=0.9,en;q=0.8,ar;q=0.7',
       'ru,en;q=0.9,en-GB;q=0.8,en-US;q=0.7,kk;q=0.6',
       'ru-RU,ru;q=0.9,kk-RU;q=0.8,kk;q=0.7,en-US;q=0.6,en;q=0.5',
       'ru-RU,ru;q=0.9,be-RU;q=0.8,be;q=0.7,en-US;q=0.6,en;q=0.5',
       'ru-GB,ru-RU;q=0.9,ru;q=0.8,en-US;q=0.7,en;q=0.6',
       'ru,en;q=0.9,ja;q=0.8,de;q=0.7,es;q=0.6', 'ru;q=0.6', 'ru;q=0.5',
       'ru;q=0.9', 'ru;q=0.7', 'ru;q=0.8',
       'ru-RU,ru;q=0.9,en-IE;q=0.8,en-US;q=0.7,en;q=0.6',
       'en-IN,en-US;q=0.9,en;q=0.8', 'en-in',
       'ru-RU,ru;q=0.9,fr-TN;q=0.8,fr;q=0.7,en-US;q=0.6,en;q=0.5'],
      dtype=object)

In [42]:
train_part1["timezone"].loc[train_part1["target"] == 1].unique()

array([-1., 28., 31., 13., 14., 20.,  3., 39., 26.,  1., 27., 32., 33.,
       36.,  2.,  0., 18., 21., 16., 23., 17.,  8., 10., 42., 24., 15.,
       47., 38.])

In [44]:
train_part1["timezone"].loc[train_part1["target"] == 0].unique()

array([-1.000e+00,  3.100e+01,  3.800e+01,  2.800e+01,  1.000e+01,
        3.300e+01,  1.600e+01,  8.000e+00,  1.300e+01,  2.700e+01,
        2.600e+01,  2.300e+01,  4.200e+01,  4.000e+01,  7.600e+01,
        8.300e+01,  5.800e+01,  3.200e+01,  4.600e+01,  7.000e+01,
        6.400e+01,  5.700e+01,  7.100e+01,  5.500e+01,  6.500e+01,
        2.000e+01,  3.900e+01,  2.100e+01,  3.000e+00,  1.800e+01,
        0.000e+00,  1.200e+01,  1.400e+01,  9.000e+00,  2.400e+01,
        1.500e+01,  1.900e+01,  2.900e+01,  1.000e+00,  1.100e+01,
        7.000e+00,  2.000e+00,  2.500e+01,  3.600e+01,  9.700e+01,
        5.000e+00,  1.700e+01,  3.500e+01,  4.000e+00,  3.700e+01,
        1.080e+02,  7.900e+01,  6.000e+00,  4.100e+01,  6.700e+01,
        5.000e+01,  4.300e+01,  3.400e+01,  4.400e+01,  3.000e+01,
        4.800e+01,  1.090e+02,  7.300e+01,  9.900e+01,  7.700e+01,
        5.200e+01,  5.900e+01,  6.000e+01,  5.600e+01,  5.088e+03,
        6.600e+01,  4.500e+01,  2.200e+01,  5.300e+01,  8.059e+03,
        1.017e+03,  7.500e+01,  6.900e+01,  7.800e+01,  6.300e+01,
        7.400e+01,  6.100e+01,  9.400e+01,  8.900e+01,  4.700e+01,
        1.146e+03,  4.860e+02,  1.000e+02,  2.960e+02,  8.510e+02,
        8.960e+02,  2.330e+02,  9.800e+01,  9.630e+02,  1.050e+02,
        8.500e+01,  5.100e+01,  5.400e+01,  1.010e+02,  5.850e+02,
        8.400e+01,  3.366e+03,  3.580e+02,  1.100e+02])

In [45]:
train_part1["device_system_version"].loc[train_part1["target"] == 1].unique()

array([-1, '13', '12', '16.7.11', '14', '18.4.1', '18.3.1', '10', '11',
       '9', '15', '8.1.0', '18.3.2', '7.0', '17.6.1', '18.3', '18.1.1',
       '18.2.1', '8.0.0', '14.7.1', '16.1.1', '7.1.1', '18.0', '15.3.1',
       '18.1', '16.3.1', '16.4.1', '17.4.1', '17.5.1', '16.7.10', '15.6',
       '7.1.2', '15.8.3', '16.7', '18.4'], dtype=object)

In [46]:
train_part1["device_system_version"].loc[train_part1["target"] == 0].unique()

array([-1, '13', '12', '14', '15', '9', '16.7.10', '11', '16.7.11',
       '18.0', '18.1.1', '18.3.2', '18.4.1', '18.5', '8.1.0', '17.6.1',
       '10', '18.3.1', '18.2', '18.2.1', '16.1.1', '16.6', '18.4', '16.1',
       '18.3', '17.4.1', '15.8.4', '16.2', '17.5.1', '15.8.3', '7.0',
       '15.2.1', '7.1.1', '16.0', '8.0.0', '18.0.1', '15.8', '15.7.9',
       '6.0.1', '18.1', '17.7.1', '16.5.1', '17.3.1', '7.1.2', '16.3.1',
       '17.7', '14.2.1', '17.2.1', '15.1', '15.4.1', '16.7.6', '15.0.2',
       '16.7.8', '16.7', '14.5.1', '17.0.2', '15.6.1', '17.7.2', '17.7.4',
       '17.7.5', '17.6', '17.4', '17.2', '15.5', '14.7.1', '15.8.2',
       '15.4', '14.4.1', '10.0', '16.6.1', '14.8.1', '15.7.3', '15.3.1',
       '16.7.2', '14.4', '16.1.2', '15.0', '17.7.6', '15.6', '17.1.1',
       '17.0.1', '16.4', '17.7.3', '17.7.7', '17.7.8', '17.1', '14.6',
       '16.7.1', '16.0.3', '17.1.2', '15.3', '15.0.1', '16.7.7', '16.5',
       '17.0.3', '17.5', '16.4.1', '16.3', '14.1', '17.3', '15.2',
       '16.7.5', '9.0', '15.1.1', '15.7.2', '16.0.2', '11.0', '12.0',
       '16.7.3', '14.4.2', '15.7.1', '16', '14.8', '6.0', '15.7.7',
       '14.5', '15.7'], dtype=object)

In [40]:
train_part1["operating_system_type"].loc[train_part1["target"] == 1].unique()

array([-1.,  6.,  4.,  9.,  7.,  2.,  8.,  3.])

In [41]:
train_part1["operating_system_type"].loc[train_part1["target"] == 0].unique()

array([-1.,  6.,  2.,  4.,  8.,  7.,  9.,  3.,  1.,  0., 10.,  5.])

In [38]:
train_part1["battery"].loc[train_part1["target"] == 1].unique()

array([-1, 'not available', '100%', '46%', '28.999999999999996%', '92%',
       '93%', '41%', '40%', '39%', '95%', '83%', '99%', '54%', '52%',
       '48%', '64%', '34%', '22%', '84%', '78%', '38%', '51%', '98%',
       '96%', '32%', '25%', '26%', '21%', '65%', '43%', '5%', '66%',
       '70%', '80%', '47%', '86%', '15%', '90%', '61%', '42%', '94%',
       '67%', '82%', '53%', '57.99999999999999%', '9%', '63%',
       '56.99999999999999%', '12%', '73%', '17%', '45%',
       '7.000000000000001%', '24%', '97%', '71%', '30%',
       '56.00000000000001%', '62%', '68%', '36%', '91%', 'NaN%', '75%',
       '19%', '77%', '72%', '79%', '50%', '89%'], dtype=object)

In [39]:
train_part1["battery"].loc[train_part1["target"] == 0].unique()

array([-1, 'not available', '93%', '100%', '76%', '73%', '69%',
       '55.00000000000001%', '54%', '53%', '61%', '56.00000000000001%',
       '42%', '87%', '51%', '43%', '98%', '59%', '6%', '77%', '99%',
       '80%', '89%', '30%', '96%', '36%', '62%', '72%', '47%', '46%',
       '79%', '82%', '78%', '52%', '22%', '4%', '85%', '49%', '71%',
       '92%', '94%', '97%', '18%', '63%', '81%', '84%', '64%', '39%',
       '66%', '33%', '90%', '28.000000000000004%', '60%', '40%', '32%',
       '20%', '34%', '70%', '38%', '48%', '74%', '86%', '41%', '67%',
       '14.000000000000002%', '57.99999999999999%', '25%', '35%', '50%',
       '95%', '44%', '9%', '17%', '45%', '65%', '68%', '91%', '83%',
       '75%', '12%', '27%', '16%', '28.999999999999996%', '23%', '19%',
       '37%', '21%', '56.99999999999999%', '88%', '26%', '24%', '8%',
       '11%', '10%', '0%', '15%', '31%', '1%', '2%', '5%', '3%', '13%',
       'NaN%', '7.000000000000001%',
       ':0%,User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,reducedMotion:false,mouseTimingV1:[[2.772588722239781,2.833213344056216,5.484960471420001,3.38368026142383,1.3704421636579194]],userAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,webdriver:false,language:ru-RU,colorDepth:24,deviceMemory:8,pixelRatio:1,hardwareConcurrency:4,screenResolution:1920,1080,availableScreenResolution:1920,1040,timezoneOffset:-180,timezone:Europe/Moscow,sessionStorage:true,localStorage:true,indexedDb:true,openDatabase:false,platform:Win32,plugins:Adobe Acrobat,Adobe PDF Plug-In For Firefox and Netscape 24.5.20399,application/pdf,pdf,application/vnd.adobe.pdfxml,pdfxml,application/vnd.adobe.x-mars,mars,application/vnd.fdf,fdf,application/vnd.adobe.xfdf,xfdf,application/vnd.adobe.xdp+xml,xdp,application/vnd.adobe.xfd+xml,xfd,Alipay Security Control 3,Alipay Security Control,application/x-alisecctrl-plugin,*,Alipay security control,npaliedit,application/aliedit,,Chromium PDF Plugin,Portable Document Format,application/x-google-chrome-pdf,pdf,Chromium PDF Viewer,,application/pdf,pdf,Microsoft Office 2016,The plugin allows you to have a better experience with Microsoft SharePoint,application/x-sharepoint,,application/x-sharepoint-uc,,Microsoft® Windows Media Player Firefox Plugin,np-mswmp,application/x-ms-wmp,*,application/asx,*,video/x-ms-asf-plugin,*,application/x-mplayer2,*,video/x-ms-asf,asf,asx,*,video/x-ms-wm,wm,*,audio/x-ms-wma,wma,*,audio/x-ms-wax,wax,*,video/x-ms-wmv,wmv,*,video/x-ms-wvx,wvx,*,iTrusChina iTrusPTA,XEnroll,iEnroll,hwPTA,UKeyInstalls Firefox Plugin,iTrusPTA',
       ':100%,User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,reducedMotion:false,mouseTimingV1:[[2.772588722239781,2.833213344056216,2.833213344056216,2.9058899974175274,0.4128512054517482],[2.772588722239781,2.833213344056216,3.6050398140853943,3.136713203893845,1.1954089692217564],[2.7058230259275198,2.833213344056216,4.211551134008321,3.1557078927149895,0.7981887381425107]],userAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,webdriver:false,language:ru-RU,colorDepth:24,deviceMemory:4,pixelRatio:1,hardwareConcurrency:8,screenResolution:900,1440,availableScreenResolution:860,1440,timezoneOffset:-180,timezone:Europe/Moscow,sessionStorage:true,localStorage:true,indexedDb:true,openDatabase:false,platform:Win32,plugins:Alipay Security Control 3,Alipay Security Control,application/x-alisecctrl-plugin,*,Alipay security control,npaliedit,application/aliedit,,Chromium PDF Plugin,Portable Document Format,application/x-google-chrome-pdf,pdf,Chromium PDF Viewer,,application/pdf,pdf,CryptoPro CAdES NPAPI Browser Plug-in,CryptoPro CAdES NPAPI Browser Plug-in,application/x-cades,,Microsoft® Windows Media Player Firefox Plugin,np-mswmp,application/x-ms-wmp,*,application/asx,*,video/x-ms-asf-plugin,*,application/x-mplayer2,*,video/x-ms-asf,asf,asx,*,video/x-ms-wm,wm,*,audio/x-ms-wma,wma,*,audio/x-ms-wax,wax,*,video/x-ms-wmv,wmv,*,video/x-ms-wvx,wvx,*,Shockwave Flash,Shockwave Flash 32.0 r0,application/x-shockwave-flash,swf,application/futuresplash,spl,iTrusChina iTrusPTA,XEnroll,iEnroll,hwPTA,UKeyInstalls Firefox Plugin,iTrusPTA',
       ':100%,User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,reducedMotion:false,mouseTimingV1:[[2.772588722239781,2.833213344056216,2.833213344056216,2.8421159104939644,0.14389368590311588],[2.772588722239781,2.833213344056216,3.337280695907213,2.9510307495766006,0.5279652647041363],[2.772588722239781,2.833213344056216,3.836611560560854,3.0496050788346,0.7159712071442551]],userAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,webdriver:false,language:ru-RU,colorDepth:24,deviceMemory:4,pixelRatio:1,hardwareConcurrency:8,screenResolution:900,1440,availableScreenResolution:860,1440,timezoneOffset:-180,timezone:Europe/Moscow,sessionStorage:true,localStorage:true,indexedDb:true,openDatabase:false,platform:Win32,plugins:Alipay Security Control 3,Alipay Security Control,application/x-alisecctrl-plugin,*,Alipay security control,npaliedit,application/aliedit,,Chromium PDF Plugin,Portable Document Format,application/x-google-chrome-pdf,pdf,Chromium PDF Viewer,,application/pdf,pdf,CryptoPro CAdES NPAPI Browser Plug-in,CryptoPro CAdES NPAPI Browser Plug-in,application/x-cades,,Microsoft® Windows Media Player Firefox Plugin,np-mswmp,application/x-ms-wmp,*,application/asx,*,video/x-ms-asf-plugin,*,application/x-mplayer2,*,video/x-ms-asf,asf,asx,*,video/x-ms-wm,wm,*,audio/x-ms-wma,wma,*,audio/x-ms-wax,wax,*,video/x-ms-wmv,wmv,*,video/x-ms-wvx,wvx,*,Shockwave Flash,Shockwave Flash 32.0 r0,application/x-shockwave-flash,swf,application/futuresplash,spl,iTrusChina iTrusPTA,XEnroll,iEnroll,hwPTA,UKeyInstalls Firefox Plugin,iTrusPTA',
       ':100%,reducedMotion:false,mouseTimingV1:[],userAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,webdriver:false,language:ru-RU,colorDepth:24,deviceMemory:8,pixelRatio:1,hardwareConcurrency:4,screenResolution:900,1600,availableScreenResolution:860,1600,timezoneOffset:-180,timezone:Europe/Moscow,sessionStorage:true,localStorage:true,indexedDb:true,addBehavior:false,openDatabase:false,cpuClass:not available,platform:Win32,plugins:Alipay Security Control 3,Alipay Security Control,application/x-alisecctrl-plugin,*,Alipay security control,npaliedit,application/aliedit,,Chromium PDF Plugin,Portable Document Format,application/x-google-chrome-pdf,pdf,Chromium PDF Viewer,,application/pdf,pdf,Microsoft Office,The plugin allows you to have a better experience with Microsoft SharePoint,application/x-sharepoint,,application/x-sharepoint-uc,,Microsoft® Windows Media Player Firefox Plugin,np-mswmp,application/x-ms-wmp,*,application/asx,*,video/x-ms-asf-plugin,*,application/x-mplayer2,*,video/x-ms-asf,asf,asx,*,video/x-ms-wm,wm,*,audio/x-ms-wma,wma,*,audio/x-ms-wax,wax,*,video/x-ms-wmv,wmv,*,video/x-ms-wvx,wvx,*,PDF-XChangeВ® Editor,PDF-XChange Editor Netscape Gecko Plugin,application/pdf,pdf,application/vnd.fdf,fdf,application/vnd.adobe.xfdf,xfdf,PDF-XChangeВ® Editor,PDF-XChange Editor Netscape Gecko Plugin,application/pdf,pdf,application/vnd.fdf,fdf,application/vnd.adobe.xfdf,xfdf,Shockwave Flash,Shockwave Flash 32.0 r0,application/x-shockwave-flash,swf,application/futuresplash,spl,Shockwave Flash,Shockwave Flash 32.0 r0,application/x-shockwave-flash,swf,application/futuresplash,spl,iTrusChina iTrusPTA,XEnroll,iEnroll,hwPTA,UKeyInstalls Firefox Plugin,iTrusPTA',
       ':100%,User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,reducedMotion:false,mouseTimingV1:[],userAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,webdriver:false,language:ru-RU,colorDepth:24,deviceMemory:8,pixelRatio:1,hardwareConcurrency:4,screenResolution:900,1600,availableScreenResolution:860,1600,timezoneOffset:-180,timezone:Europe/Moscow,sessionStorage:true,localStorage:true,indexedDb:true,openDatabase:false,platform:Win32,plugins:Alipay Security Control 3,Alipay Security Control,application/x-alisecctrl-plugin,*,Alipay security control,npaliedit,application/aliedit,,Chromium PDF Plugin,Portable Document Format,application/x-google-chrome-pdf,pdf,Chromium PDF Viewer,,application/pdf,pdf,Microsoft Office,The plugin allows you to have a better experience with Microsoft SharePoint,application/x-sharepoint,,application/x-sharepoint-uc,,Microsoft® Windows Media Player Firefox Plugin,np-mswmp,application/x-ms-wmp,*,application/asx,*,video/x-ms-asf-plugin,*,application/x-mplayer2,*,video/x-ms-asf,asf,asx,*,video/x-ms-wm,wm,*,audio/x-ms-wma,wma,*,audio/x-ms-wax,wax,*,video/x-ms-wmv,wmv,*,video/x-ms-wvx,wvx,*,PDF-XChangeВ® Editor,PDF-XChange Editor Netscape Gecko Plugin,application/pdf,pdf,application/vnd.fdf,fdf,application/vnd.adobe.xfdf,xfdf,PDF-XChangeВ® Editor,PDF-XChange Editor Netscape Gecko Plugin,application/pdf,pdf,application/vnd.fdf,fdf,application/vnd.adobe.xfdf,xfdf,Shockwave Flash,Shockwave Flash 32.0 r0,application/x-shockwave-flash,swf,application/futuresplash,spl,Shockwave Flash,Shockwave Flash 32.0 r0,application/x-shockwave-flash,swf,application/futuresplash,spl,iTrusChina iTrusPTA,XEnroll,iEnroll,hwPTA,UKeyInstalls Firefox Plugin,iTrusPTA',
       ':100%,User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,reducedMotion:false,mouseTimingV1:[[2.70805020110221,2.833213344056216,3.4811217321331034,2.9410721418523376,0.2736365524791759]],userAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,webdriver:false,language:ru-RU,colorDepth:24,deviceMemory:8,pixelRatio:1,hardwareConcurrency:4,screenResolution:900,1600,availableScreenResolution:860,1600,timezoneOffset:-180,timezone:Europe/Moscow,sessionStorage:true,localStorage:true,indexedDb:true,openDatabase:false,platform:Win32,plugins:Alipay Security Control 3,Alipay Security Control,application/x-alisecctrl-plugin,*,Alipay security control,npaliedit,application/aliedit,,Chromium PDF Plugin,Portable Document Format,application/x-google-chrome-pdf,pdf,Chromium PDF Viewer,,application/pdf,pdf,Microsoft Office,The plugin allows you to have a better experience with Microsoft SharePoint,application/x-sharepoint,,application/x-sharepoint-uc,,Microsoft® Windows Media Player Firefox Plugin,np-mswmp,application/x-ms-wmp,*,application/asx,*,video/x-ms-asf-plugin,*,application/x-mplayer2,*,video/x-ms-asf,asf,asx,*,video/x-ms-wm,wm,*,audio/x-ms-wma,wma,*,audio/x-ms-wax,wax,*,video/x-ms-wmv,wmv,*,video/x-ms-wvx,wvx,*,PDF-XChangeВ® Editor,PDF-XChange Editor Netscape Gecko Plugin,application/pdf,pdf,application/vnd.fdf,fdf,application/vnd.adobe.xfdf,xfdf,PDF-XChangeВ® Editor,PDF-XChange Editor Netscape Gecko Plugin,application/pdf,pdf,application/vnd.fdf,fdf,application/vnd.adobe.xfdf,xfdf,Shockwave Flash,Shockwave Flash 32.0 r0,application/x-shockwave-flash,swf,application/futuresplash,spl,Shockwave Flash,Shockwave Flash 32.0 r0,application/x-shockwave-flash,swf,application/futuresplash,spl,iTrusChina iTrusPTA,XEnroll,iEnroll,hwPTA,UKeyInstalls Firefox Plugin,iTrusPTA',
       ':100%,User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,reducedMotion:false,mouseTimingV1:[[2.70805020110221,2.833213344056216,2.8903717578961645,2.995555661489224,0.7960741499346485],[2.772588722239781,2.833213344056216,2.8903717578961645,2.863598699696401,0.24813021951139563],[2.772588722239781,2.833213344056216,4.54000193512409,3.2093592728755627,0.852849******7714],[2.772588722239781,2.833213344056216,4.905165027024939,3.323481944372623,1.025357408608629]],userAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,webdriver:false,language:ru-RU,colorDepth:24,deviceMemory:4,pixelRatio:1.25,hardwareConcurrency:4,screenResolution:864,1536,availableScreenResolution:824,1536,timezoneOffset:-180,timezone:Europe/Moscow,sessionStorage:true,localStorage:true,indexedDb:true,openDatabase:false,platform:Win32,plugins:Alipay Security Control 3,Alipay Security Control,application/x-alisecctrl-plugin,*,Alipay security control,npaliedit,application/aliedit,,Chromium PDF Plugin,Portable Document Format,application/x-google-chrome-pdf,pdf,Chromium PDF Viewer,,application/pdf,pdf,Microsoft Office,The plugin allows you to have a better experience with Microsoft SharePoint,application/x-sharepoint,,application/x-sharepoint-uc,,Microsoft® Windows Media Player Firefox Plugin,np-mswmp,application/x-ms-wmp,*,application/asx,*,video/x-ms-asf-plugin,*,application/x-mplayer2,*,video/x-ms-asf,asf,asx,*,video/x-ms-wm,wm,*,audio/x-ms-wma,wma,*,audio/x-ms-wax,wax,*,video/x-ms-wmv,wmv,*,video/x-ms-wvx,wvx,*,iTrusChina iTrusPTA,XEnroll,iEnroll,hwPTA,UKeyInstalls Firefox Plugin,iTrusPTA',
       ':100%,User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,reducedMotion:false,mouseTimingV1:[[2.6735537653587342,2.833213344056216,5.618506924058682,3.3339152130042544,1.2648584377357082],[2.70805020110221,2.833213344056216,2.995732273553991,2.9924826363795938,0.6994849211408323],[2.7403194616709956,2.833213344056216,2.8903717578961645,2.9551170680358134,0.750670379123022],[2.6020033435383976,2.833213344056216,3.7628199875207677,2.953943******6933,0.6842022222968636]],userAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,webdriver:false,language:ru-RU,colorDepth:24,deviceMemory:4,pixelRatio:1.25,hardwareConcurrency:4,screenResolution:864,1536,availableScreenResolution:824,1536,timezoneOffset:-180,timezone:Europe/Moscow,sessionStorage:true,localStorage:true,indexedDb:true,openDatabase:false,platform:Win32,plugins:Alipay Security Control 3,Alipay Security Control,application/x-alisecctrl-plugin,*,Alipay security control,npaliedit,application/aliedit,,Chromium PDF Plugin,Portable Document Format,application/x-google-chrome-pdf,pdf,Chromium PDF Viewer,,application/pdf,pdf,Microsoft Office,The plugin allows you to have a better experience with Microsoft SharePoint,application/x-sharepoint,,application/x-sharepoint-uc,,Microsoft® Windows Media Player Firefox Plugin,np-mswmp,application/x-ms-wmp,*,application/asx,*,video/x-ms-asf-plugin,*,application/x-mplayer2,*,video/x-ms-asf,asf,asx,*,video/x-ms-wm,wm,*,audio/x-ms-wma,wma,*,audio/x-ms-wax,wax,*,video/x-ms-wmv,wmv,*,video/x-ms-wvx,wvx,*,iTrusChina iTrusPTA,XEnroll,iEnroll,hwPTA,UKeyInstalls Firefox Plugin,iTrusPTA',
       ':100%,User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,reducedMotion:false,mouseTimingV1:[],userAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,webdriver:false,language:ru-RU,colorDepth:24,deviceMemory:4,pixelRatio:1.25,hardwareConcurrency:4,screenResolution:864,1536,availableScreenResolution:824,1536,timezoneOffset:-180,timezone:Europe/Moscow,sessionStorage:true,localStorage:true,indexedDb:true,openDatabase:false,platform:Win32,plugins:Alipay Security Control 3,Alipay Security Control,application/x-alisecctrl-plugin,*,Alipay security control,npaliedit,application/aliedit,,Chromium PDF Plugin,Portable Document Format,application/x-google-chrome-pdf,pdf,Chromium PDF Viewer,,application/pdf,pdf,Microsoft Office,The plugin allows you to have a better experience with Microsoft SharePoint,application/x-sharepoint,,application/x-sharepoint-uc,,Microsoft® Windows Media Player Firefox Plugin,np-mswmp,application/x-ms-wmp,*,application/asx,*,video/x-ms-asf-plugin,*,application/x-mplayer2,*,video/x-ms-asf,asf,asx,*,video/x-ms-wm,wm,*,audio/x-ms-wma,wma,*,audio/x-ms-wax,wax,*,video/x-ms-wmv,wmv,*,video/x-ms-wvx,wvx,*,iTrusChina iTrusPTA,XEnroll,iEnroll,hwPTA,UKeyInstalls Firefox Plugin,iTrusPTA',
       ':100%,User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,reducedMotion:false,mouseTimingV1:[[2.4260151319598084,2.833213344056216,3.469626973020754,2.970406401900303,0.571167******1252],[2.772588722239781,2.833213344056216,2.833213344056216,2.8789422654245276,0.37046896359650905],[2.772588722239781,2.833213344056216,3.511434043041321,3.1347256964266266,1.1574201867169511],[2.772588722239781,2.833213344056216,4.292051948349432,3.21694894313704,1.1727718784371524],[2.772588722239781,2.833213344056216,2.8903717578961645,2.842290844587494,0.15664817663953606]],userAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,webdriver:false,language:ru-RU,colorDepth:24,deviceMemory:4,pixelRatio:1.25,hardwareConcurrency:4,screenResolution:864,1536,availableScreenResolution:824,1536,timezoneOffset:-180,timezone:Europe/Moscow,sessionStorage:true,localStorage:true,indexedDb:true,openDatabase:false,platform:Win32,plugins:Alipay Security Control 3,Alipay Security Control,application/x-alisecctrl-plugin,*,Alipay security control,npaliedit,application/aliedit,,Chromium PDF Plugin,Portable Document Format,application/x-google-chrome-pdf,pdf,Chromium PDF Viewer,,application/pdf,pdf,Microsoft Office,The plugin allows you to have a better experience with Microsoft SharePoint,application/x-sharepoint,,application/x-sharepoint-uc,,Microsoft® Windows Media Player Firefox Plugin,np-mswmp,application/x-ms-wmp,*,application/asx,*,video/x-ms-asf-plugin,*,application/x-mplayer2,*,video/x-ms-asf,asf,asx,*,video/x-ms-wm,wm,*,audio/x-ms-wma,wma,*,audio/x-ms-wax,wax,*,video/x-ms-wmv,wmv,*,video/x-ms-wvx,wvx,*,iTrusChina iTrusPTA,XEnroll,iEnroll,hwPTA,UKeyInstalls Firefox Plugin,iTrusPTA',
       ':100%,User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,reducedMotion:false,mouseTimingV1:[[2.772588722239781,2.833213344056216,4.437014061278168,3.254431060880351,1.4409819950888938]],userAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36,webdriver:false,language:ru-RU,colorDepth:24,deviceMemory:4,pixelRatio:1.25,hardwareConcurrency:4,screenResolution:864,1536,availableScreenResolution:824,1536,timezoneOffset:-180,timezone:Europe/Moscow,sessionStorage:true,localStorage:true,indexedDb:true,openDatabase:false,platform:Win32,plugins:Alipay Security Control 3,Alipay Security Control,application/x-alisecctrl-plugin,*,Alipay security control,npaliedit,application/aliedit,,Chromium PDF Plugin,Portable Document Format,application/x-google-chrome-pdf,pdf,Chromium PDF Viewer,,application/pdf,pdf,Microsoft Office,The plugin allows you to have a better experience with Microsoft SharePoint,application/x-sharepoint,,application/x-sharepoint-uc,,Microsoft® Windows Media Player Firefox Plugin,np-mswmp,application/x-ms-wmp,*,application/asx,*,video/x-ms-asf-plugin,*,application/x-mplayer2,*,video/x-ms-asf,asf,asx,*,video/x-ms-wm,wm,*,audio/x-ms-wma,wma,*,audio/x-ms-wax,wax,*,video/x-ms-wmv,wmv,*,video/x-ms-wvx,wvx,*,iTrusChina iTrusPTA,XEnroll,iEnroll,hwPTA,UKeyInstalls Firefox Plugin,iTrusPTA',

In [35]:
train_part1["screen_size"].loc[train_part1["target"] == 1].unique()

array([-1, '1080x2158', '1080x2168', '375x812', '1200x2394', '414x896',
       '1080x2207', '1080x2270', '1080x2122', '1220x2482', '390x844',
       '1080x2242', '720x1393', '1080x2186', '1080x2107', '1080x2177',
       '720x1384', '1080x2194', '1080x2176', '1080x2232', '720x1444',
       '720x1465', '720x1438', '720x1449', '1080x2115', '720x1460',
       '1080x2095', '1440x2723', '1080x2226', '1080x2224', '720x1600',
       '1080x2116', '720x1440', '1080x2170', '720x1280', '1080x2130',
       '1080x2209', '1080x2125', '720x1448', '1080x2153', '1080x2195',
       '1080x2166', '720x1507', '393x852', '1080x2238', '1080x2460',
       '1220x2560', '1080x2360', '720x1411', '1080x2134', '1080x2181',
       '720x1467', '900x1600', '1080x2132', '1080x2173', '720x1477',
       '1220x2712', '1080x2179', '1080x2131', '1080x2098', '1080x2030',
       '1080x2352', '1080x2163', '1080x2161', '540x960', '720x1372',
       '1080x2094', '1440x2730', '1080x2340', '1080x2160', '1080x2189',
       '720x1365', '1100x2325', '1080x2280', '1080x2208', '720x1486',
       '1080x2192', '720x1352', '1080x2139', '1080x2271', '1080x2172',
       '720x1369', '720x1452', '720x1458', '1920x1080', '1080x1920',
       '1080x2114', '720x1447', '1080x2190', '1080x2245', '720x1472',
       '1080x2121', '1080x2220', '480x888', '1080x2002', '720x1552',
       '1080x2146', '1080x2241', '1440x2913', '1080x2140', '1080x2150',
       '1080x2156', '1080x2167', '720x1436', '1080x2262', '1080x2183',
       '720x1529', '1080x2640', '720x1446', '1080x2293', '720x1478',
       '1080x2128', '1080x2289', '720x1196', '1080x2400', '1080x2328',
       '1080x2218', '430x932', '1220x2450', '720x1461', '720x1396',
       '1080x2143', '1080x2202', '1080x2032', '1080x2385', '1080x2110',
       '1080x2011', '1080x2097', '720x1470', '1080x2159', '1080x2180',
       '992x1200', '2000x1134', '800x1256', '720x1480', '1100x2206',
       '1080x2214', '1080x2148', '720x1451', '1080x2269', '1272x2604',
       '428x926', '720x1488', '720x1474', '720x1469', '720x1561',
       '1080x2292', '720x1456', '576x1024', '720x1505', '1200x2412',
       '720x1454', '1080x2109', '1080x2412', '1080x2137', '1084x2186',
       '1080x2273', '720x1423', '1080x2058', '720x1371', '720x1567',
       '1440x2808', '720x1481', '1080x2342', '1080x2196', '720x1445',
       '1440x2768', '1080x2144', '1080x2016', '1200x2538', '1080x2106',
       '720x1528', '320x568', '1080x2225', '720x1434', '1080x2120',
       '1080x2185', '720x1339', '375x667', '720x1426', '1080x2200',
       '1080x2316', '720x1422', '720x1455', '1080x2276', '1080x2020',
       '1080x2191', '1080x2171', '720x1358', '1080x2205', '1220x2530',
       '1080x2113', '1080x2049', '1080x2169', '1080x2119', '1080x2124',
       '1080x2154', '720x1382', '1080x2436', '1080x2184', '1080x2307',
       '1080x2025', '720x1184', '1200x1844', '1080x2060', '1080x2117',
       '1080x2291', '1080x2230', '1080x2283', '720x1539', '720x1473',
       '1080x2141', '1080x2076', '720x1437', '720x1555', '1440x2960',
       '1080x2138', '1200x2670', '1200x2506', '1440x2839', '1080x2304',
       '1080x2223', '720x1459', '1080x2201', '1080x2198', '720x1520',
       '1080x2129', '1280x2800', '1212x2517', '1080x2216', '1080x2178',
       '1080x2199', '720x1471', '1080x2263', '1200x2664', '1080x2043',
       '2156x2344', '1080x2324', '720x1532', '720x1502', '1080x2193',
       '1440x2733', '1080x2164', '1200x2000', '1080x2145', '1080x2142',
       '1224x2700', '720x1370', '1220x2582', '720x1344', '800x1216',
       '480x896', '1080x2256', '720x1424', '720x1495', '720x1489',
       '1080x2298', '640x1195', '720x1354', '1080x2038', '1080x2268',
       '1080x2069', '1080x2068', '720x1604', '1440x2848', '1220x2468',
       '1080x2151', '1080x2259', '320x693', '720x1536', '720x1550',
       '1080x2089', '720x1399', '1080x2136', '1220x2476', '1080x2222',
       '1080x2174', '1080x2331', '720x1364', '1200x2470', '720x1568',
       '720x1540', '1080x2290', '720x1410', '960x2379', '1084x2302',
       '1080x2305', '1200x1972', '1080x1794', '720x1483', '720x1466',
       '720x1405', '1080x2062', '1600x900', '1080x2206', '402x874',
       '1080x2310', '1080x2265', '720x1442', '1080x2162', '1080x2037',
       '1080x2309', '1200x1848', '720x1406', '720x1508', '1080x2112',
       '720x1244', '1080x2065', '1080x2402', '720x1601', '1080x2312',
       '1080x2182', '720x1518', '1080x2343', '1080x1999', '918x1158',
       '720x1362', '720x1453', '720x1428', '720x1432', '1200x2554',
       '1080x2090', '1080x2300', '1080x2219', '720x1433', '1080x2187',
       '720x1492', '1080x2212', '1080x2165', '1228x2444', '1088x2175',
       '1080x2118', '720x1392', '1080x2266', '1440x2800', '810x1580',
       '1220x2466', '1200x2408', '1080x2282', '1080x1776', '1200x1892',
       '720x1425', '1080x2249', '1228x2578', '1440x2880', '1200x2522',
       '1340x736', '800x1276'], dtype=object)

In [32]:
train_part1["screen_size"].loc[train_part1["target"] == 0].unique()

array([-1, '1080x2180', '720x1507', ..., '666x1287', '1312x2707',
       '1312x2848'], shape=(1523,), dtype=object)

Получили обработанный набор данных, теперь можно переходить к обучению моделей.

In [ ]:
# train_part1.to_parquet("ClearData/train_part1.parquet", index=False, engine="fastparquet")